export enum QUERIES {
  ACTIVE_PROGRAM = 'activeProgram',
  ENTITLEMENT = 'entitlement',
  FEATURE_FLAGS = 'featureFlags',
  MOVEMENT_LOGS = 'movementLogs',
  MOVEMENTS = 'movements',
  PATTERN_DEBT = 'patternDebt',
  PROGRAM = 'program',
  PROGRAM_PROGRESS = 'programProgress',
  PROGRAMS = 'programs',
  SWING_PROGRESSION = 'swingProgression',
  USER_MOVEMENTS = 'userMovements',
  WORKOUT_LOG = 'workoutLog',
  WORKOUT_LOGS = 'workoutLogs',
  WORKOUT_LOGS_INFINITE = 'workoutLogsInfinite',
}
