export enum QUERIES {
  ACTIVE_PROGRAM = 'activeProgram',
  ENTITLEMENT = 'entitlement',
  FEATURE_FLAGS = 'featureFlags',
  GHOST_SESSION = 'ghostSession',
  MOVEMENT = 'movement',
  MOVEMENT_HISTORY = 'movementHistory',
  MOVEMENT_LOGS = 'movementLogs',
  MOVEMENTS = 'movements',
  MODALITY_DEBT = 'modalityDebt',
  PATTERN_DEBT = 'patternDebt',
  PROGRAM = 'program',
  PROGRAM_PROGRESS = 'programProgress',
  PROGRAMS = 'programs',
  QUEUED_PROGRAMS = 'queuedPrograms',
  SPOTIFY_CONNECTION = 'spotifyConnection',
  SPOTIFY_NOW_PLAYING = 'spotifyNowPlaying',
  USER_EQUIPMENT = 'userEquipment',
  USER_MOVEMENTS = 'userMovements',
  WORKOUT_LOG = 'workoutLog',
  WORKOUT_LOGS = 'workoutLogs',
  WORKOUT_LOGS_INFINITE = 'workoutLogsInfinite',
}
