-- Unilateral lower-body work as its own axis.
--
-- Until now "one side at a time" was inferred from `weight_two_value = 0` — the
-- builder's sentinel for a single bell in one hand. That conflates the arm axis
-- with the leg axis, so a double kettlebell single-leg Romanian deadlift, a
-- goblet reverse lunge, and a bodyweight pistol squat could never mirror their
-- rungs. `unilateral_lower` names the leg axis directly and is independent of
-- "# Primary Items" / "Single or Double Arm".
--
-- Source of truth is scripts/data/movements.csv; the backfill below is
-- generated with `node scripts/ingest-movements.mjs --emit-unilateral-sql`.

ALTER TABLE public.movements
  ADD COLUMN IF NOT EXISTS unilateral_lower boolean NOT NULL DEFAULT false;

INSERT INTO public.movements ("Movement", "Primary Equipment", "# Primary Items", "Single or Double Arm", "Target Muscle Group", "Difficulty Level", "Movement Pattern #1", pattern_credits, modality_credits)
SELECT v.name, v.equipment, v.items, v.arm, v.muscle, v.difficulty, v.pattern, v.credits, v.modalities
FROM (VALUES
  ('Kettlebell Swing', 'Kettlebell', 1, 'Double Arm', 'Hamstrings', 'Beginner', 'Hip Hinge', ARRAY['hinge']::text[], ARRAY['ballistic', 'conditioning']::text[]),
  ('One-Arm Kettlebell Swing', 'Kettlebell', 1, 'Single Arm', 'Hamstrings', 'Intermediate', 'Hip Hinge', ARRAY['hinge']::text[], ARRAY['ballistic', 'conditioning']::text[]),
  ('Double Kettlebell Swing', 'Kettlebell', 2, 'Double Arm', 'Hamstrings', 'Intermediate', 'Hip Hinge', ARRAY['hinge']::text[], ARRAY['ballistic', 'conditioning']::text[]),
  ('Alternating Kettlebell Swing', 'Kettlebell', 1, 'Single Arm', 'Hamstrings', 'Intermediate', 'Hip Hinge', ARRAY['hinge']::text[], ARRAY['ballistic', 'conditioning']::text[]),
  ('Kettlebell Dead Clean', 'Kettlebell', 1, 'Single Arm', 'Hamstrings', 'Intermediate', 'Hip Hinge', ARRAY['hinge']::text[], ARRAY['ballistic']::text[]),
  ('Kettlebell Hang Clean', 'Kettlebell', 1, 'Single Arm', 'Hamstrings', 'Intermediate', 'Hip Hinge', ARRAY['hinge']::text[], ARRAY['ballistic']::text[]),
  ('One-Arm Kettlebell Clean', 'Kettlebell', 1, 'Single Arm', 'Hamstrings', 'Intermediate', 'Hip Hinge', ARRAY['hinge']::text[], ARRAY['ballistic']::text[]),
  ('Bottoms-Up Kettlebell Clean', 'Kettlebell', 1, 'Single Arm', 'Forearms', 'Intermediate', 'Hip Hinge', ARRAY['hinge']::text[], ARRAY['ballistic']::text[]),
  ('Bottoms-Up Kettlebell Clean From Hang', 'Kettlebell', 1, 'Single Arm', 'Forearms', 'Intermediate', 'Hip Hinge', ARRAY['hinge']::text[], ARRAY['ballistic']::text[]),
  ('Double Kettlebell Clean', 'Kettlebell', 2, 'Double Arm', 'Shoulders', 'Intermediate', 'Hip Hinge', ARRAY['hinge']::text[], ARRAY['ballistic']::text[]),
  ('Double Kettlebell Dead Clean', 'Kettlebell', 2, 'Double Arm', 'Hamstrings', 'Intermediate', 'Hip Hinge', ARRAY['hinge']::text[], ARRAY['ballistic']::text[]),
  ('Double Kettlebell Alternating Hang Clean', 'Kettlebell', 2, 'Double Arm', 'Hamstrings', 'Intermediate', 'Hip Hinge', ARRAY['hinge']::text[], ARRAY['ballistic']::text[]),
  ('Alternating Kettlebell Hang Clean', 'Kettlebell', 2, 'Double Arm', 'Hamstrings', 'Intermediate', 'Hip Hinge', ARRAY['hinge']::text[], ARRAY['ballistic']::text[]),
  ('One-Arm Kettlebell Snatch', 'Kettlebell', 1, 'Single Arm', 'Shoulders', 'Expert', 'Hip Hinge', ARRAY['hinge']::text[], ARRAY['ballistic', 'conditioning']::text[]),
  ('One-Arm Kettlebell Split Snatch', 'Kettlebell', 1, 'Single Arm', 'Shoulders', 'Expert', 'Hip Hinge', ARRAY['hinge']::text[], ARRAY['ballistic', 'conditioning']::text[]),
  ('Kettlebell Dead Snatch', 'Kettlebell', 1, 'Single Arm', 'Shoulders', 'Expert', 'Hip Hinge', ARRAY['hinge']::text[], ARRAY['ballistic', 'conditioning']::text[]),
  ('Kettlebell Hang Snatch', 'Kettlebell', 1, 'Single Arm', 'Shoulders', 'Expert', 'Hip Hinge', ARRAY['hinge']::text[], ARRAY['ballistic', 'conditioning']::text[]),
  ('Double Kettlebell Snatch', 'Kettlebell', 2, 'Double Arm', 'Shoulders', 'Expert', 'Hip Hinge', ARRAY['hinge']::text[], ARRAY['ballistic', 'conditioning']::text[]),
  ('Kettlebell Sumo High Pull', 'Kettlebell', 1, 'Double Arm', 'Trapezius', 'Intermediate', 'Hip Hinge', ARRAY['hinge']::text[], ARRAY['ballistic']::text[]),
  ('One-Arm Kettlebell High Pull', 'Kettlebell', 1, 'Single Arm', 'Trapezius', 'Intermediate', 'Hip Hinge', ARRAY['hinge']::text[], ARRAY['ballistic']::text[]),
  ('Double Kettlebell High Pull', 'Kettlebell', 2, 'Double Arm', 'Trapezius', 'Intermediate', 'Hip Hinge', ARRAY['hinge']::text[], ARRAY['ballistic']::text[]),
  ('Kettlebell Snatch Pull', 'Kettlebell', 1, 'Single Arm', 'Trapezius', 'Intermediate', 'Hip Hinge', ARRAY['hinge']::text[], ARRAY['ballistic', 'conditioning']::text[]),
  ('Kettlebell Figure 8', 'Kettlebell', 1, 'Double Arm', 'Abdominals', 'Intermediate', 'Hip Hinge', ARRAY['hinge']::text[], ARRAY['mobility']::text[]),
  ('Kettlebell Pass Between The Legs', 'Kettlebell', 1, 'Double Arm', 'Abdominals', 'Intermediate', 'Hip Hinge', ARRAY['hinge']::text[], ARRAY['mobility']::text[]),
  ('Kettlebell Pirate Ships', 'Kettlebell', 1, 'Double Arm', 'Shoulders', 'Beginner', 'Hip Hinge', ARRAY['hinge']::text[], ARRAY['mobility']::text[]),
  ('Kettlebell Hike Pass', 'Kettlebell', 1, 'Double Arm', 'Hamstrings', 'Beginner', 'Hip Hinge', ARRAY['hinge']::text[], ARRAY['ballistic']::text[]),
  ('Kettlebell Deadlift', 'Kettlebell', 1, 'Double Arm', 'Hamstrings', 'Beginner', 'Hip Hinge', ARRAY['hinge']::text[], ARRAY['grind']::text[]),
  ('Kettlebell Sumo Deadlift', 'Kettlebell', 1, 'Double Arm', 'Hamstrings', 'Beginner', 'Hip Hinge', ARRAY['hinge']::text[], ARRAY['grind']::text[]),
  ('Kettlebell Suitcase Deadlift', 'Kettlebell', 2, 'Double Arm', 'Hamstrings', 'Beginner', 'Hip Hinge', ARRAY['hinge']::text[], ARRAY['grind']::text[]),
  ('Kettlebell Romanian Deadlift', 'Kettlebell', 2, 'Double Arm', 'Hamstrings', 'Beginner', 'Hip Hinge', ARRAY['hinge']::text[], ARRAY['grind']::text[]),
  ('Double Kettlebell Romanian Deadlift', 'Kettlebell', 2, 'Double Arm', 'Hamstrings', 'Beginner', 'Hip Hinge', ARRAY['hinge']::text[], ARRAY['grind']::text[]),
  ('Kettlebell Single-Leg Deadlift', 'Kettlebell', 1, 'Single Arm', 'Hamstrings', 'Intermediate', 'Hip Hinge', ARRAY['hinge']::text[], ARRAY['grind']::text[]),
  ('Kettlebell Single-Leg Romanian Deadlift', 'Kettlebell', 1, 'Single Arm', 'Hamstrings', 'Intermediate', 'Hip Hinge', ARRAY['hinge']::text[], ARRAY['grind']::text[]),
  ('Kettlebell Goblet Single-Leg Romanian Deadlift', 'Kettlebell', 1, 'Double Arm', 'Hamstrings', 'Intermediate', 'Hip Hinge', ARRAY['hinge']::text[], ARRAY['grind']::text[]),
  ('Double Kettlebell Single-Leg Romanian Deadlift', 'Kettlebell', 2, 'Double Arm', 'Hamstrings', 'Expert', 'Hip Hinge', ARRAY['hinge']::text[], ARRAY['grind']::text[]),
  ('Kettlebell Staggered Deadlift', 'Kettlebell', 1, 'Single Arm', 'Hamstrings', 'Intermediate', 'Hip Hinge', ARRAY['hinge']::text[], ARRAY['grind']::text[]),
  ('Kettlebell Good Morning', 'Kettlebell', 1, 'Double Arm', 'Hamstrings', 'Intermediate', 'Hip Hinge', ARRAY['hinge']::text[], ARRAY['grind']::text[]),
  ('Goblet Squat', 'Kettlebell', 1, 'Double Arm', 'Quadriceps', 'Beginner', 'Knee Dominant', ARRAY['squat']::text[], ARRAY['grind']::text[]),
  ('Double Kettlebell Front Squat', 'Kettlebell', 2, 'Double Arm', 'Quadriceps', 'Intermediate', 'Knee Dominant', ARRAY['squat']::text[], ARRAY['grind']::text[]),
  ('Kettlebell Pistol Squat', 'Kettlebell', 1, 'Double Arm', 'Quadriceps', 'Expert', 'Knee Dominant', ARRAY['squat']::text[], ARRAY['grind']::text[]),
  ('One-Arm Overhead Kettlebell Squat', 'Kettlebell', 1, 'Single Arm', 'Quadriceps', 'Expert', 'Knee Dominant', ARRAY['squat']::text[], ARRAY['grind']::text[]),
  ('Kettlebell Front Rack Squat', 'Kettlebell', 1, 'Single Arm', 'Quadriceps', 'Intermediate', 'Knee Dominant', ARRAY['squat']::text[], ARRAY['grind']::text[]),
  ('Kettlebell Cossack Squat', 'Kettlebell', 1, 'Double Arm', 'Adductors', 'Intermediate', 'Knee Dominant', ARRAY['squat']::text[], ARRAY['grind', 'mobility']::text[]),
  ('Kettlebell Goblet Reverse Lunge', 'Kettlebell', 1, 'Double Arm', 'Quadriceps', 'Beginner', 'Knee Dominant', ARRAY['squat']::text[], ARRAY['grind']::text[]),
  ('Kettlebell Racked Reverse Lunge', 'Kettlebell', 1, 'Single Arm', 'Quadriceps', 'Intermediate', 'Knee Dominant', ARRAY['squat']::text[], ARRAY['grind']::text[]),
  ('Kettlebell Goblet Forward Lunge', 'Kettlebell', 1, 'Double Arm', 'Quadriceps', 'Beginner', 'Knee Dominant', ARRAY['squat']::text[], ARRAY['grind']::text[]),
  ('Kettlebell Racked Forward Lunge', 'Kettlebell', 1, 'Single Arm', 'Quadriceps', 'Intermediate', 'Knee Dominant', ARRAY['squat']::text[], ARRAY['grind']::text[]),
  ('Kettlebell Goblet Walking Lunge', 'Kettlebell', 1, 'Double Arm', 'Quadriceps', 'Beginner', 'Knee Dominant', ARRAY['squat']::text[], ARRAY['grind']::text[]),
  ('Kettlebell Overhead Reverse Lunge', 'Kettlebell', 1, 'Single Arm', 'Shoulders', 'Intermediate', 'Knee Dominant', ARRAY['squat']::text[], ARRAY['grind']::text[]),
  ('Double Kettlebell Front Rack Reverse Lunge', 'Kettlebell', 2, 'Double Arm', 'Quadriceps', 'Intermediate', 'Knee Dominant', ARRAY['squat']::text[], ARRAY['grind']::text[]),
  ('Kettlebell Curtsy Lunge', 'Kettlebell', 1, 'Single Arm', 'Glutes', 'Intermediate', 'Knee Dominant', ARRAY['squat']::text[], ARRAY['grind']::text[]),
  ('Kettlebell Bulgarian Split Squat', 'Kettlebell', 1, 'Double Arm', 'Quadriceps', 'Intermediate', 'Knee Dominant', ARRAY['squat']::text[], ARRAY['grind']::text[]),
  ('Kettlebell Front Rack Bulgarian Split Squat', 'Kettlebell', 1, 'Single Arm', 'Quadriceps', 'Intermediate', 'Knee Dominant', ARRAY['squat']::text[], ARRAY['grind']::text[]),
  ('Double Kettlebell Bulgarian Split Squat', 'Kettlebell', 2, 'Double Arm', 'Quadriceps', 'Expert', 'Knee Dominant', ARRAY['squat']::text[], ARRAY['grind']::text[]),
  ('Kettlebell Goblet Step-Up', 'Kettlebell', 1, 'Double Arm', 'Quadriceps', 'Beginner', 'Knee Dominant', ARRAY['squat']::text[], ARRAY['grind']::text[]),
  ('Kettlebell Lateral Lunge', 'Kettlebell', 1, 'Double Arm', 'Adductors', 'Intermediate', 'Knee Dominant', ARRAY['squat']::text[], ARRAY['grind']::text[]),
  ('Kettlebell Lunge Pass Through', 'Kettlebell', 1, 'Double Arm', 'Quadriceps', 'Intermediate', 'Knee Dominant', ARRAY['squat']::text[], ARRAY['mobility']::text[]),
  ('Kettlebell Goblet Split Squat', 'Kettlebell', 1, 'Double Arm', 'Quadriceps', 'Beginner', 'Knee Dominant', ARRAY['squat']::text[], ARRAY['grind']::text[]),
  ('Kettlebell Racked Split Squat', 'Kettlebell', 1, 'Single Arm', 'Quadriceps', 'Intermediate', 'Knee Dominant', ARRAY['squat']::text[], ARRAY['grind']::text[]),
  ('Kettlebell Racked Step-Up', 'Kettlebell', 1, 'Single Arm', 'Quadriceps', 'Intermediate', 'Knee Dominant', ARRAY['squat']::text[], ARRAY['grind']::text[]),
  ('Kettlebell Goblet Curtsy Lunge', 'Kettlebell', 1, 'Double Arm', 'Glutes', 'Beginner', 'Knee Dominant', ARRAY['squat']::text[], ARRAY['grind']::text[]),
  ('Double Kettlebell Front Rack Split Squat', 'Kettlebell', 2, 'Double Arm', 'Quadriceps', 'Intermediate', 'Knee Dominant', ARRAY['squat']::text[], ARRAY['grind']::text[]),
  ('Double Kettlebell Front Rack Step-Up', 'Kettlebell', 2, 'Double Arm', 'Quadriceps', 'Intermediate', 'Knee Dominant', ARRAY['squat']::text[], ARRAY['grind']::text[]),
  ('Double Kettlebell Suitcase Reverse Lunge', 'Kettlebell', 2, 'Double Arm', 'Quadriceps', 'Intermediate', 'Knee Dominant', ARRAY['squat']::text[], ARRAY['grind']::text[]),
  ('Double Kettlebell Front Rack Cossack Squat', 'Kettlebell', 2, 'Double Arm', 'Adductors', 'Expert', 'Knee Dominant', ARRAY['squat']::text[], ARRAY['grind']::text[]),
  ('Double Kettlebell Military Press', 'Kettlebell', 2, 'Double Arm', 'Shoulders', 'Intermediate', 'Vertical Push', ARRAY['push']::text[], ARRAY['grind']::text[]),
  ('One-Arm Kettlebell Military Press', 'Kettlebell', 1, 'Single Arm', 'Shoulders', 'Intermediate', 'Vertical Push', ARRAY['push']::text[], ARRAY['grind']::text[]),
  ('Alternating Kettlebell Press', 'Kettlebell', 2, 'Double Arm', 'Shoulders', 'Intermediate', 'Vertical Push', ARRAY['push']::text[], ARRAY['grind']::text[]),
  ('Kettlebell Seesaw Press', 'Kettlebell', 2, 'Double Arm', 'Shoulders', 'Intermediate', 'Vertical Push', ARRAY['push']::text[], ARRAY['grind']::text[]),
  ('Kettlebell See-Saw Push Press', 'Kettlebell', 2, 'Double Arm', 'Shoulders', 'Intermediate', 'Vertical Push', ARRAY['push']::text[], ARRAY['ballistic']::text[]),
  ('Kettlebell Arnold Press', 'Kettlebell', 1, 'Single Arm', 'Shoulders', 'Intermediate', 'Vertical Push', ARRAY['push']::text[], ARRAY['grind']::text[]),
  ('Kettlebell Seated Press', 'Kettlebell', 1, 'Single Arm', 'Shoulders', 'Intermediate', 'Vertical Push', ARRAY['push']::text[], ARRAY['grind']::text[]),
  ('Kettlebell Half-Kneeling Press', 'Kettlebell', 1, 'Single Arm', 'Shoulders', 'Intermediate', 'Vertical Push', ARRAY['push']::text[], ARRAY['grind']::text[]),
  ('Kettlebell Tall-Kneeling Press', 'Kettlebell', 1, 'Single Arm', 'Shoulders', 'Intermediate', 'Vertical Push', ARRAY['push']::text[], ARRAY['grind']::text[]),
  ('Kettlebell Z Press', 'Kettlebell', 1, 'Single Arm', 'Shoulders', 'Intermediate', 'Vertical Push', ARRAY['push']::text[], ARRAY['grind']::text[]),
  ('Double Kettlebell Z Press', 'Kettlebell', 2, 'Double Arm', 'Shoulders', 'Intermediate', 'Vertical Push', ARRAY['push']::text[], ARRAY['grind']::text[]),
  ('One-Arm Kettlebell Para Press', 'Kettlebell', 1, 'Single Arm', 'Shoulders', 'Intermediate', 'Vertical Push', ARRAY['push']::text[], ARRAY['grind']::text[]),
  ('One-Arm Kettlebell Push Press', 'Kettlebell', 1, 'Single Arm', 'Shoulders', 'Intermediate', 'Vertical Push', ARRAY['push']::text[], ARRAY['ballistic']::text[]),
  ('Double Kettlebell Push Press', 'Kettlebell', 2, 'Double Arm', 'Shoulders', 'Intermediate', 'Vertical Push', ARRAY['push']::text[], ARRAY['ballistic']::text[]),
  ('Double Kettlebell Push Jerk', 'Kettlebell', 2, 'Double Arm', 'Shoulders', 'Intermediate', 'Vertical Push', ARRAY['push']::text[], ARRAY['ballistic']::text[]),
  ('One-Arm Kettlebell Jerk', 'Kettlebell', 1, 'Single Arm', 'Shoulders', 'Intermediate', 'Vertical Push', ARRAY['push']::text[], ARRAY['ballistic']::text[]),
  ('One-Arm Kettlebell Split Jerk', 'Kettlebell', 1, 'Single Arm', 'Shoulders', 'Intermediate', 'Vertical Push', ARRAY['push']::text[], ARRAY['ballistic']::text[]),
  ('One-Arm Kettlebell Clean and Jerk', 'Kettlebell', 1, 'Single Arm', 'Shoulders', 'Intermediate', 'Vertical Push', ARRAY['push']::text[], ARRAY['ballistic', 'grind']::text[]),
  ('Double Kettlebell Jerk', 'Kettlebell', 2, 'Double Arm', 'Shoulders', 'Intermediate', 'Vertical Push', ARRAY['push']::text[], ARRAY['ballistic']::text[]),
  ('Kettlebell Thruster', 'Kettlebell', 1, 'Double Arm', 'Shoulders', 'Intermediate', 'Vertical Push', ARRAY['push']::text[], ARRAY['ballistic', 'conditioning']::text[]),
  ('Double Kettlebell Thruster', 'Kettlebell', 2, 'Double Arm', 'Shoulders', 'Intermediate', 'Vertical Push', ARRAY['push']::text[], ARRAY['ballistic', 'conditioning']::text[]),
  ('Kettlebell Clean and Press', 'Kettlebell', 1, 'Single Arm', 'Shoulders', 'Intermediate', 'Vertical Push', ARRAY['push']::text[], ARRAY['ballistic', 'grind']::text[]),
  ('Double Kettlebell Clean and Press', 'Kettlebell', 2, 'Double Arm', 'Shoulders', 'Intermediate', 'Vertical Push', ARRAY['push']::text[], ARRAY['ballistic', 'grind']::text[]),
  ('Kettlebell Sots Press', 'Kettlebell', 1, 'Single Arm', 'Shoulders', 'Expert', 'Vertical Push', ARRAY['push']::text[], ARRAY['grind']::text[]),
  ('Kettlebell Bottoms-Up Press', 'Kettlebell', 1, 'Single Arm', 'Shoulders', 'Intermediate', 'Vertical Push', ARRAY['push']::text[], ARRAY['grind']::text[]),
  ('Kettlebell Bent Press', 'Kettlebell', 1, 'Single Arm', 'Shoulders', 'Expert', 'Vertical Push', ARRAY['push']::text[], ARRAY['grind']::text[]),
  ('One-Arm Kettlebell Floor Press', 'Kettlebell', 1, 'Single Arm', 'Chest', 'Intermediate', 'Horizontal Push', ARRAY['push']::text[], ARRAY['grind']::text[]),
  ('Extended Range One-Arm Kettlebell Floor Press', 'Kettlebell', 1, 'Single Arm', 'Chest', 'Beginner', 'Horizontal Push', ARRAY['push']::text[], ARRAY['grind']::text[]),
  ('Leg-Over Kettlebell Floor Press', 'Kettlebell', 1, 'Single Arm', 'Chest', 'Intermediate', 'Horizontal Push', ARRAY['push']::text[], ARRAY['grind']::text[]),
  ('Alternating Kettlebell Floor Press', 'Kettlebell', 2, 'Double Arm', 'Chest', 'Beginner', 'Horizontal Push', ARRAY['push']::text[], ARRAY['grind']::text[]),
  ('Double Kettlebell Floor Press', 'Kettlebell', 2, 'Double Arm', 'Chest', 'Beginner', 'Horizontal Push', ARRAY['push']::text[], ARRAY['grind']::text[]),
  ('Kettlebell Bench Press', 'Kettlebell', 1, 'Single Arm', 'Chest', 'Intermediate', 'Horizontal Push', ARRAY['push']::text[], ARRAY['grind']::text[]),
  ('Double Kettlebell Bench Press', 'Kettlebell', 2, 'Double Arm', 'Chest', 'Intermediate', 'Horizontal Push', ARRAY['push']::text[], ARRAY['grind']::text[]),
  ('Kettlebell Push-Up', 'Kettlebell', 2, 'Double Arm', 'Chest', 'Intermediate', 'Horizontal Push', ARRAY['push']::text[], ARRAY['grind']::text[]),
  ('Plyo Kettlebell Push-Up', 'Kettlebell', 2, 'Double Arm', 'Chest', 'Expert', 'Horizontal Push', ARRAY['push']::text[], ARRAY['ballistic', 'conditioning']::text[]),
  ('One-Arm Kettlebell Row', 'Kettlebell', 1, 'Single Arm', 'Back', 'Intermediate', 'Horizontal Pull', ARRAY['pull']::text[], ARRAY['grind']::text[]),
  ('Double Kettlebell Row', 'Kettlebell', 2, 'Double Arm', 'Back', 'Intermediate', 'Horizontal Pull', ARRAY['pull']::text[], ARRAY['grind']::text[]),
  ('Alternating Kettlebell Row', 'Kettlebell', 2, 'Double Arm', 'Back', 'Intermediate', 'Horizontal Pull', ARRAY['pull']::text[], ARRAY['grind']::text[]),
  ('Kettlebell Renegade Row', 'Kettlebell', 2, 'Double Arm', 'Back', 'Expert', 'Horizontal Pull', ARRAY['pull']::text[], ARRAY['grind']::text[]),
  ('Alternating Renegade Row', 'Kettlebell', 2, 'Double Arm', 'Back', 'Expert', 'Horizontal Pull', ARRAY['pull']::text[], ARRAY['grind']::text[]),
  ('Kettlebell Gorilla Row', 'Kettlebell', 2, 'Double Arm', 'Back', 'Intermediate', 'Horizontal Pull', ARRAY['pull']::text[], ARRAY['grind']::text[]),
  ('Kettlebell Suitcase Carry', 'Kettlebell', 1, 'Single Arm', 'Forearms', 'Beginner', 'Loaded Carry', ARRAY['carry']::text[], ARRAY['grind', 'conditioning']::text[]),
  ('Kettlebell Farmer''s Carry', 'Kettlebell', 2, 'Double Arm', 'Forearms', 'Beginner', 'Loaded Carry', ARRAY['carry']::text[], ARRAY['grind', 'conditioning']::text[]),
  ('Kettlebell Racked Carry', 'Kettlebell', 1, 'Single Arm', 'Shoulders', 'Intermediate', 'Loaded Carry', ARRAY['carry']::text[], ARRAY['grind', 'conditioning']::text[]),
  ('Kettlebell Double Rack Carry', 'Kettlebell', 2, 'Double Arm', 'Shoulders', 'Intermediate', 'Loaded Carry', ARRAY['carry']::text[], ARRAY['grind', 'conditioning']::text[]),
  ('Kettlebell Overhead Carry', 'Kettlebell', 1, 'Single Arm', 'Shoulders', 'Intermediate', 'Loaded Carry', ARRAY['carry']::text[], ARRAY['grind', 'conditioning']::text[]),
  ('Kettlebell Double Overhead Carry', 'Kettlebell', 2, 'Double Arm', 'Shoulders', 'Expert', 'Loaded Carry', ARRAY['carry']::text[], ARRAY['grind', 'conditioning']::text[]),
  ('Kettlebell Waiter Carry', 'Kettlebell', 1, 'Single Arm', 'Shoulders', 'Intermediate', 'Loaded Carry', ARRAY['carry']::text[], ARRAY['grind', 'conditioning']::text[]),
  ('Kettlebell Bottoms-Up Carry', 'Kettlebell', 1, 'Single Arm', 'Forearms', 'Intermediate', 'Loaded Carry', ARRAY['carry']::text[], ARRAY['grind', 'conditioning']::text[]),
  ('Kettlebell Mixed Rack Carry', 'Kettlebell', 2, 'Double Arm', 'Forearms', 'Intermediate', 'Loaded Carry', ARRAY['carry']::text[], ARRAY['grind', 'conditioning']::text[]),
  ('Kettlebell Suitcase March', 'Kettlebell', 1, 'Single Arm', 'Abdominals', 'Beginner', 'Loaded Carry', ARRAY['carry']::text[], ARRAY['grind', 'conditioning']::text[]),
  ('Double Kettlebell Farmer March', 'Kettlebell', 2, 'Double Arm', 'Forearms', 'Beginner', 'Loaded Carry', ARRAY['carry']::text[], ARRAY['grind', 'conditioning']::text[]),
  ('Kettlebell Windmill', 'Kettlebell', 1, 'Single Arm', 'Abdominals', 'Intermediate', 'Rotational', ARRAY['rotation']::text[], ARRAY['grind', 'mobility']::text[]),
  ('Advanced Kettlebell Windmill', 'Kettlebell', 1, 'Single Arm', 'Abdominals', 'Intermediate', 'Rotational', ARRAY['rotation']::text[], ARRAY['grind', 'mobility']::text[]),
  ('Kettlebell Overhead Windmill', 'Kettlebell', 1, 'Single Arm', 'Abdominals', 'Expert', 'Rotational', ARRAY['rotation']::text[], ARRAY['grind', 'mobility']::text[]),
  ('Double Kettlebell Windmill', 'Kettlebell', 2, 'Double Arm', 'Abdominals', 'Intermediate', 'Rotational', ARRAY['rotation']::text[], ARRAY['grind', 'mobility']::text[]),
  ('Kettlebell Halo', 'Kettlebell', 1, 'Double Arm', 'Shoulders', 'Beginner', 'Rotational', ARRAY['rotation']::text[], ARRAY['mobility']::text[]),
  ('Kettlebell Half-Kneeling Halo', 'Kettlebell', 1, 'Double Arm', 'Shoulders', 'Beginner', 'Rotational', ARRAY['rotation']::text[], ARRAY['mobility']::text[]),
  ('Kettlebell Around The Body', 'Kettlebell', 1, 'Double Arm', 'Abdominals', 'Beginner', 'Rotational', ARRAY['rotation']::text[], ARRAY['mobility']::text[]),
  ('Kettlebell Russian Twist', 'Kettlebell', 1, 'Double Arm', 'Abdominals', 'Intermediate', 'Rotational', ARRAY['rotation']::text[], ARRAY['grind']::text[]),
  ('Kettlebell Wood Chop', 'Kettlebell', 1, 'Double Arm', 'Abdominals', 'Beginner', 'Rotational', ARRAY['rotation']::text[], ARRAY['grind']::text[]),
  ('Kettlebell Side Bend', 'Kettlebell', 1, 'Single Arm', 'Abdominals', 'Beginner', 'Anti-Rotation', ARRAY['core']::text[], ARRAY['grind']::text[]),
  ('Kettlebell Turkish Get-Up', 'Kettlebell', 1, 'Single Arm', 'Shoulders', 'Intermediate', 'Vertical Push', ARRAY['get_up', 'push', 'rotation']::text[], ARRAY['grind', 'mobility']::text[]),
  ('Kettlebell Turkish Get-Up (Lunge Style)', 'Kettlebell', 1, 'Single Arm', 'Shoulders', 'Intermediate', 'Vertical Push', ARRAY['get_up', 'push', 'rotation']::text[], ARRAY['grind', 'mobility']::text[]),
  ('Kettlebell Turkish Get-Up (Squat Style)', 'Kettlebell', 1, 'Single Arm', 'Shoulders', 'Intermediate', 'Vertical Push', ARRAY['get_up', 'push', 'rotation']::text[], ARRAY['grind', 'mobility']::text[]),
  ('Half Kettlebell Get-Up', 'Kettlebell', 1, 'Single Arm', 'Shoulders', 'Beginner', 'Vertical Push', ARRAY['get_up', 'push', 'rotation']::text[], ARRAY['grind', 'mobility']::text[]),
  ('Push-Up', 'Bodyweight', 1, 'Double Arm', 'Chest', 'Beginner', 'Horizontal Push', ARRAY['push']::text[], ARRAY['grind']::text[]),
  ('Wide-Grip Push-Up', 'Bodyweight', 1, 'Double Arm', 'Chest', 'Beginner', 'Horizontal Push', ARRAY['push']::text[], ARRAY['grind']::text[]),
  ('Close-Grip Push-Up', 'Bodyweight', 1, 'Double Arm', 'Triceps', 'Intermediate', 'Horizontal Push', ARRAY['push']::text[], ARRAY['grind']::text[]),
  ('Diamond Push-Up', 'Bodyweight', 1, 'Double Arm', 'Triceps', 'Intermediate', 'Horizontal Push', ARRAY['push']::text[], ARRAY['grind']::text[]),
  ('Incline Push-Up', 'Bodyweight', 1, 'Double Arm', 'Chest', 'Beginner', 'Horizontal Push', ARRAY['push']::text[], ARRAY['grind']::text[]),
  ('Decline Push-Up', 'Bodyweight', 1, 'Double Arm', 'Chest', 'Beginner', 'Horizontal Push', ARRAY['push']::text[], ARRAY['grind']::text[]),
  ('Knee Push-Up', 'Bodyweight', 1, 'Double Arm', 'Chest', 'Beginner', 'Horizontal Push', ARRAY['push']::text[], ARRAY['grind']::text[]),
  ('Wall Push-Up', 'Bodyweight', 1, 'Double Arm', 'Chest', 'Beginner', 'Horizontal Push', ARRAY['push']::text[], ARRAY['grind']::text[]),
  ('Staggered Push-Up', 'Bodyweight', 1, 'Double Arm', 'Chest', 'Beginner', 'Horizontal Push', ARRAY['push']::text[], ARRAY['grind']::text[]),
  ('Clock Push-Up', 'Bodyweight', 1, 'Double Arm', 'Chest', 'Intermediate', 'Horizontal Push', ARRAY['push']::text[], ARRAY['grind']::text[]),
  ('Spiderman Push-Up', 'Bodyweight', 1, 'Double Arm', 'Chest', 'Intermediate', 'Horizontal Push', ARRAY['push']::text[], ARRAY['grind']::text[]),
  ('Hindu Push-Up', 'Bodyweight', 1, 'Double Arm', 'Chest', 'Intermediate', 'Horizontal Push', ARRAY['push']::text[], ARRAY['mobility']::text[]),
  ('Plyometric Push-Up', 'Bodyweight', 1, 'Double Arm', 'Chest', 'Intermediate', 'Horizontal Push', ARRAY['push']::text[], ARRAY['ballistic', 'conditioning']::text[]),
  ('Clap Push-Up', 'Bodyweight', 1, 'Double Arm', 'Chest', 'Intermediate', 'Horizontal Push', ARRAY['push']::text[], ARRAY['ballistic', 'conditioning']::text[]),
  ('Archer Push-Up', 'Bodyweight', 1, 'Double Arm', 'Chest', 'Expert', 'Horizontal Push', ARRAY['push']::text[], ARRAY['grind']::text[]),
  ('Pseudo Planche Push-Up', 'Bodyweight', 1, 'Double Arm', 'Shoulders', 'Expert', 'Horizontal Push', ARRAY['push']::text[], ARRAY['grind']::text[]),
  ('Single-Arm Push-Up', 'Bodyweight', 1, 'Single Arm', 'Chest', 'Expert', 'Horizontal Push', ARRAY['push']::text[], ARRAY['grind']::text[]),
  ('Push-Up to Side Plank', 'Bodyweight', 1, 'Double Arm', 'Chest', 'Beginner', 'Horizontal Push', ARRAY['push']::text[], ARRAY['grind']::text[]),
  ('Body Triceps Press', 'Bodyweight', 1, 'Double Arm', 'Triceps', 'Beginner', 'Horizontal Push', ARRAY['push']::text[], ARRAY['grind']::text[]),
  ('Bench Dips', 'Bodyweight', 1, 'Double Arm', 'Triceps', 'Beginner', 'Vertical Push', ARRAY['push']::text[], ARRAY['grind']::text[]),
  ('Triceps Dips', 'Bodyweight', 1, 'Double Arm', 'Triceps', 'Beginner', 'Vertical Push', ARRAY['push']::text[], ARRAY['grind']::text[]),
  ('Straight Bar Dip', 'Bodyweight', 1, 'Double Arm', 'Triceps', 'Intermediate', 'Vertical Push', ARRAY['push']::text[], ARRAY['grind']::text[]),
  ('Korean Dip', 'Bodyweight', 1, 'Double Arm', 'Triceps', 'Expert', 'Vertical Push', ARRAY['push']::text[], ARRAY['grind']::text[]),
  ('Handstand Push-Up', 'Bodyweight', 1, 'Double Arm', 'Shoulders', 'Expert', 'Vertical Push', ARRAY['push']::text[], ARRAY['grind']::text[]),
  ('Pike Push-Up', 'Bodyweight', 1, 'Double Arm', 'Shoulders', 'Intermediate', 'Vertical Push', ARRAY['push']::text[], ARRAY['grind']::text[]),
  ('Wall Walk', 'Bodyweight', 1, 'Double Arm', 'Shoulders', 'Intermediate', 'Vertical Push', ARRAY['push']::text[], ARRAY['conditioning']::text[]),
  ('Wall Handstand Hold', 'Bodyweight', 1, 'Double Arm', 'Shoulders', 'Intermediate', 'Vertical Push', ARRAY['push']::text[], ARRAY['grind']::text[]),
  ('Pull-Up', 'Bodyweight', 1, 'Double Arm', 'Back', 'Beginner', 'Vertical Pull', ARRAY['pull']::text[], ARRAY['grind']::text[]),
  ('Chin-Up', 'Bodyweight', 1, 'Double Arm', 'Back', 'Beginner', 'Vertical Pull', ARRAY['pull']::text[], ARRAY['grind']::text[]),
  ('Neutral-Grip Pull-Up', 'Bodyweight', 1, 'Double Arm', 'Back', 'Beginner', 'Vertical Pull', ARRAY['pull']::text[], ARRAY['grind']::text[]),
  ('Wide-Grip Pull-Up', 'Bodyweight', 1, 'Double Arm', 'Back', 'Intermediate', 'Vertical Pull', ARRAY['pull']::text[], ARRAY['grind']::text[]),
  ('V-Bar Pull-Up', 'Bodyweight', 1, 'Double Arm', 'Back', 'Beginner', 'Vertical Pull', ARRAY['pull']::text[], ARRAY['grind']::text[]),
  ('Commando Pull-Up', 'Bodyweight', 1, 'Double Arm', 'Back', 'Intermediate', 'Vertical Pull', ARRAY['pull']::text[], ARRAY['grind']::text[]),
  ('Scapular Pull-Up', 'Bodyweight', 1, 'Double Arm', 'Back', 'Beginner', 'Vertical Pull', ARRAY['pull']::text[], ARRAY['grind']::text[]),
  ('Negative Pull-Up', 'Bodyweight', 1, 'Double Arm', 'Back', 'Beginner', 'Vertical Pull', ARRAY['pull']::text[], ARRAY['grind']::text[]),
  ('L-Sit Pull-Up', 'Bodyweight', 1, 'Double Arm', 'Back', 'Expert', 'Vertical Pull', ARRAY['pull']::text[], ARRAY['grind']::text[]),
  ('Archer Pull-Up', 'Bodyweight', 1, 'Double Arm', 'Back', 'Expert', 'Vertical Pull', ARRAY['pull']::text[], ARRAY['grind']::text[]),
  ('Muscle-Up', 'Bodyweight', 1, 'Double Arm', 'Back', 'Expert', 'Vertical Pull', ARRAY['pull']::text[], ARRAY['grind']::text[]),
  ('Gorilla Chin-Up Crunch', 'Bodyweight', 1, 'Double Arm', 'Abdominals', 'Intermediate', 'Vertical Pull', ARRAY['pull']::text[], ARRAY['grind']::text[]),
  ('Band Pull-Down', 'Bodyweight', 1, 'Double Arm', 'Back', 'Beginner', 'Vertical Pull', ARRAY['pull']::text[], ARRAY['grind']::text[]),
  ('Single-Arm Band Pull-Down', 'Bodyweight', 1, 'Single Arm', 'Back', 'Beginner', 'Vertical Pull', ARRAY['pull']::text[], ARRAY['grind']::text[]),
  ('Inverted Row', 'Bodyweight', 1, 'Double Arm', 'Back', 'Beginner', 'Horizontal Pull', ARRAY['pull']::text[], ARRAY['grind']::text[]),
  ('Wide-Grip Inverted Row', 'Bodyweight', 1, 'Double Arm', 'Back', 'Beginner', 'Horizontal Pull', ARRAY['pull']::text[], ARRAY['grind']::text[]),
  ('Underhand Inverted Row', 'Bodyweight', 1, 'Double Arm', 'Back', 'Beginner', 'Horizontal Pull', ARRAY['pull']::text[], ARRAY['grind']::text[]),
  ('Single-Arm Inverted Row', 'Bodyweight', 1, 'Single Arm', 'Back', 'Intermediate', 'Horizontal Pull', ARRAY['pull']::text[], ARRAY['grind']::text[]),
  ('Bodyweight Squat', 'Bodyweight', 1, 'No Arms', 'Quadriceps', 'Beginner', 'Knee Dominant', ARRAY['squat']::text[], ARRAY['grind']::text[]),
  ('Jump Squat', 'Bodyweight', 1, 'No Arms', 'Quadriceps', 'Intermediate', 'Knee Dominant', ARRAY['squat']::text[], ARRAY['ballistic', 'conditioning']::text[]),
  ('Bodyweight Pistol Squat', 'Bodyweight', 1, 'No Arms', 'Quadriceps', 'Expert', 'Knee Dominant', ARRAY['squat']::text[], ARRAY['grind']::text[]),
  ('Sissy Squat', 'Bodyweight', 1, 'No Arms', 'Quadriceps', 'Intermediate', 'Knee Dominant', ARRAY['squat']::text[], ARRAY['grind']::text[]),
  ('Shrimp Squat', 'Bodyweight', 1, 'No Arms', 'Quadriceps', 'Expert', 'Knee Dominant', ARRAY['squat']::text[], ARRAY['grind']::text[]),
  ('Single-Leg Box Squat', 'Bodyweight', 1, 'No Arms', 'Quadriceps', 'Intermediate', 'Knee Dominant', ARRAY['squat']::text[], ARRAY['grind']::text[]),
  ('Wall Sit', 'Bodyweight', 1, 'No Arms', 'Quadriceps', 'Beginner', 'Knee Dominant', ARRAY['squat']::text[], ARRAY['grind']::text[]),
  ('Cossack Squat', 'Bodyweight', 1, 'No Arms', 'Adductors', 'Intermediate', 'Knee Dominant', ARRAY['squat']::text[], ARRAY['grind', 'mobility']::text[]),
  ('Forward Lunge', 'Bodyweight', 1, 'No Arms', 'Quadriceps', 'Beginner', 'Knee Dominant', ARRAY['squat']::text[], ARRAY['grind']::text[]),
  ('Reverse Lunge', 'Bodyweight', 1, 'No Arms', 'Quadriceps', 'Beginner', 'Knee Dominant', ARRAY['squat']::text[], ARRAY['grind']::text[]),
  ('Walking Lunge', 'Bodyweight', 1, 'No Arms', 'Quadriceps', 'Beginner', 'Knee Dominant', ARRAY['squat']::text[], ARRAY['grind']::text[]),
  ('Curtsy Lunge', 'Bodyweight', 1, 'No Arms', 'Glutes', 'Beginner', 'Knee Dominant', ARRAY['squat']::text[], ARRAY['grind']::text[]),
  ('Lateral Lunge', 'Bodyweight', 1, 'No Arms', 'Adductors', 'Beginner', 'Knee Dominant', ARRAY['squat']::text[], ARRAY['grind']::text[]),
  ('Bodyweight Bulgarian Split Squat', 'Bodyweight', 1, 'No Arms', 'Quadriceps', 'Intermediate', 'Knee Dominant', ARRAY['squat']::text[], ARRAY['grind']::text[]),
  ('Step-Up with Knee Raise', 'Bodyweight', 1, 'No Arms', 'Glutes', 'Beginner', 'Knee Dominant', ARRAY['squat']::text[], ARRAY['grind']::text[]),
  ('Bodyweight Split Squat', 'Bodyweight', 1, 'No Arms', 'Quadriceps', 'Beginner', 'Knee Dominant', ARRAY['squat']::text[], ARRAY['grind']::text[]),
  ('Bodyweight Step-Up', 'Bodyweight', 1, 'No Arms', 'Quadriceps', 'Beginner', 'Knee Dominant', ARRAY['squat']::text[], ARRAY['grind']::text[]),
  ('Duck Walk', 'Bodyweight', 1, 'No Arms', 'Quadriceps', 'Intermediate', 'Knee Dominant', ARRAY['squat']::text[], ARRAY['conditioning']::text[]),
  ('High Knees', 'Bodyweight', 1, 'No Arms', 'Quadriceps', 'Beginner', 'Knee Dominant', ARRAY['squat']::text[], ARRAY['conditioning']::text[]),
  ('Squat Thrust', 'Bodyweight', 1, 'No Arms', 'Quadriceps', 'Beginner', 'Knee Dominant', ARRAY['squat']::text[], ARRAY['ballistic', 'conditioning']::text[]),
  ('Burpee', 'Bodyweight', 1, 'No Arms', 'Quadriceps', 'Intermediate', 'Knee Dominant', ARRAY['squat']::text[], ARRAY['ballistic', 'conditioning']::text[]),
  ('Bench Jump', 'Bodyweight', 1, 'No Arms', 'Quadriceps', 'Intermediate', 'Knee Dominant', ARRAY['squat']::text[], ARRAY['ballistic', 'conditioning']::text[]),
  ('Box Jump', 'Bodyweight', 1, 'No Arms', 'Quadriceps', 'Intermediate', 'Knee Dominant', ARRAY['squat']::text[], ARRAY['ballistic', 'conditioning']::text[]),
  ('Freehand Jump Squat', 'Bodyweight', 1, 'No Arms', 'Quadriceps', 'Intermediate', 'Knee Dominant', ARRAY['squat']::text[], ARRAY['ballistic', 'conditioning']::text[]),
  ('Split Jump', 'Bodyweight', 1, 'No Arms', 'Quadriceps', 'Beginner', 'Knee Dominant', ARRAY['squat']::text[], ARRAY['ballistic', 'conditioning']::text[]),
  ('Scissors Jump', 'Bodyweight', 1, 'No Arms', 'Quadriceps', 'Beginner', 'Knee Dominant', ARRAY['squat']::text[], ARRAY['ballistic', 'conditioning']::text[]),
  ('Star Jump', 'Bodyweight', 1, 'No Arms', 'Quadriceps', 'Beginner', 'Knee Dominant', ARRAY['squat']::text[], ARRAY['ballistic', 'conditioning']::text[]),
  ('Rocket Jump', 'Bodyweight', 1, 'No Arms', 'Quadriceps', 'Beginner', 'Knee Dominant', ARRAY['squat']::text[], ARRAY['ballistic', 'conditioning']::text[]),
  ('Knee Tuck Jump', 'Bodyweight', 1, 'No Arms', 'Hamstrings', 'Beginner', 'Knee Dominant', ARRAY['squat']::text[], ARRAY['ballistic', 'conditioning']::text[]),
  ('Standing Long Jump', 'Bodyweight', 1, 'No Arms', 'Quadriceps', 'Beginner', 'Knee Dominant', ARRAY['squat']::text[], ARRAY['ballistic', 'conditioning']::text[]),
  ('Lateral Bound', 'Bodyweight', 1, 'No Arms', 'Adductors', 'Beginner', 'Knee Dominant', ARRAY['squat']::text[], ARRAY['ballistic', 'conditioning']::text[]),
  ('Standing Calf Raise', 'Bodyweight', 1, 'No Arms', 'Calves', 'Beginner', 'Knee Dominant', ARRAY['squat']::text[], ARRAY['grind']::text[]),
  ('Single-Leg Calf Raise', 'Bodyweight', 1, 'No Arms', 'Calves', 'Beginner', 'Knee Dominant', ARRAY['squat']::text[], ARRAY['grind']::text[]),
  ('Glute Bridge', 'Bodyweight', 1, 'No Arms', 'Glutes', 'Beginner', 'Hip Extension', ARRAY['hinge']::text[], ARRAY['grind']::text[]),
  ('Single-Leg Glute Bridge', 'Bodyweight', 1, 'No Arms', 'Glutes', 'Beginner', 'Hip Extension', ARRAY['hinge']::text[], ARRAY['grind']::text[]),
  ('Bodyweight Hip Thrust', 'Bodyweight', 1, 'No Arms', 'Glutes', 'Beginner', 'Hip Extension', ARRAY['hinge']::text[], ARRAY['grind']::text[]),
  ('Single-Leg Hip Thrust', 'Bodyweight', 1, 'No Arms', 'Glutes', 'Intermediate', 'Hip Extension', ARRAY['hinge']::text[], ARRAY['grind']::text[]),
  ('Frog Pump', 'Bodyweight', 1, 'No Arms', 'Glutes', 'Beginner', 'Hip Extension', ARRAY['hinge']::text[], ARRAY['grind']::text[]),
  ('Glute Kickback', 'Bodyweight', 1, 'No Arms', 'Glutes', 'Beginner', 'Hip Extension', ARRAY['hinge']::text[], ARRAY['grind']::text[]),
  ('Donkey Kick', 'Bodyweight', 1, 'No Arms', 'Glutes', 'Beginner', 'Hip Extension', ARRAY['hinge']::text[], ARRAY['grind']::text[]),
  ('Fire Hydrant', 'Bodyweight', 1, 'No Arms', 'Glutes', 'Beginner', 'Hip Extension', ARRAY['hinge']::text[], ARRAY['grind']::text[]),
  ('Rear Leg Raise', 'Bodyweight', 1, 'No Arms', 'Glutes', 'Beginner', 'Hip Extension', ARRAY['hinge']::text[], ARRAY['grind']::text[]),
  ('Superman', 'Bodyweight', 1, 'No Arms', 'Back', 'Beginner', 'Hip Extension', ARRAY['hinge']::text[], ARRAY['grind']::text[]),
  ('Prone Cobra', 'Bodyweight', 1, 'No Arms', 'Back', 'Beginner', 'Hip Extension', ARRAY['hinge']::text[], ARRAY['grind']::text[]),
  ('Bodyweight Hyperextension', 'Bodyweight', 1, 'No Arms', 'Back', 'Intermediate', 'Hip Extension', ARRAY['hinge']::text[], ARRAY['grind']::text[]),
  ('Reverse Hyperextension', 'Bodyweight', 1, 'No Arms', 'Glutes', 'Intermediate', 'Hip Extension', ARRAY['hinge']::text[], ARRAY['grind']::text[]),
  ('Bird Dog', 'Bodyweight', 1, 'No Arms', 'Back', 'Beginner', 'Hip Extension', ARRAY['hinge']::text[], ARRAY['grind']::text[]),
  ('Natural Glute-Ham Raise', 'Bodyweight', 1, 'No Arms', 'Hamstrings', 'Intermediate', 'Hip Hinge', ARRAY['hinge']::text[], ARRAY['grind']::text[]),
  ('Nordic Curl', 'Bodyweight', 1, 'No Arms', 'Hamstrings', 'Expert', 'Hip Hinge', ARRAY['hinge']::text[], ARRAY['grind']::text[]),
  ('Bodyweight Good Morning', 'Bodyweight', 1, 'No Arms', 'Hamstrings', 'Beginner', 'Hip Hinge', ARRAY['hinge']::text[], ARRAY['grind']::text[]),
  ('Bodyweight Single-Leg Deadlift', 'Bodyweight', 1, 'No Arms', 'Hamstrings', 'Beginner', 'Hip Hinge', ARRAY['hinge']::text[], ARRAY['grind']::text[]),
  ('Bodyweight Single-Leg Romanian Deadlift', 'Bodyweight', 1, 'No Arms', 'Hamstrings', 'Beginner', 'Hip Hinge', ARRAY['hinge']::text[], ARRAY['grind']::text[]),
  ('Inchworm', 'Bodyweight', 1, 'Double Arm', 'Hamstrings', 'Beginner', 'Hip Hinge', ARRAY['hinge']::text[], ARRAY['mobility']::text[]),
  ('Plank', 'Bodyweight', 1, 'Double Arm', 'Abdominals', 'Beginner', 'Anti-Extension', ARRAY['core']::text[], ARRAY['grind']::text[]),
  ('Side Plank', 'Bodyweight', 1, 'Single Arm', 'Abdominals', 'Beginner', 'Anti-Rotation', ARRAY['core']::text[], ARRAY['grind']::text[]),
  ('Bear Plank', 'Bodyweight', 1, 'Double Arm', 'Abdominals', 'Beginner', 'Anti-Extension', ARRAY['core']::text[], ARRAY['grind']::text[]),
  ('Plank Shoulder Tap', 'Bodyweight', 1, 'Double Arm', 'Abdominals', 'Beginner', 'Anti-Rotation', ARRAY['core']::text[], ARRAY['grind']::text[]),
  ('Plank Up-Down', 'Bodyweight', 1, 'Double Arm', 'Abdominals', 'Intermediate', 'Anti-Extension', ARRAY['core']::text[], ARRAY['grind']::text[]),
  ('Copenhagen Plank', 'Bodyweight', 1, 'Single Arm', 'Adductors', 'Expert', 'Anti-Rotation', ARRAY['core']::text[], ARRAY['grind']::text[]),
  ('Hollow Hold', 'Bodyweight', 1, 'No Arms', 'Abdominals', 'Intermediate', 'Anti-Extension', ARRAY['core']::text[], ARRAY['grind']::text[]),
  ('Hollow Rock', 'Bodyweight', 1, 'No Arms', 'Abdominals', 'Intermediate', 'Anti-Extension', ARRAY['core']::text[], ARRAY['grind']::text[]),
  ('Mountain Climber', 'Bodyweight', 1, 'Double Arm', 'Abdominals', 'Beginner', 'Anti-Extension', ARRAY['core']::text[], ARRAY['conditioning']::text[]),
  ('Bear Crawl', 'Bodyweight', 1, 'Double Arm', 'Abdominals', 'Beginner', 'Anti-Extension', ARRAY['core']::text[], ARRAY['conditioning']::text[]),
  ('Spider Crawl', 'Bodyweight', 1, 'Double Arm', 'Abdominals', 'Beginner', 'Anti-Extension', ARRAY['core']::text[], ARRAY['conditioning']::text[]),
  ('Dead Bug', 'Bodyweight', 1, 'No Arms', 'Abdominals', 'Beginner', 'Anti-Extension', ARRAY['core']::text[], ARRAY['grind']::text[]),
  ('Russian Twist', 'Bodyweight', 1, 'No Arms', 'Abdominals', 'Intermediate', 'Rotational', ARRAY['rotation']::text[], ARRAY['grind']::text[]),
  ('Bicycle Crunch', 'Bodyweight', 1, 'No Arms', 'Abdominals', 'Beginner', 'Rotational', ARRAY['rotation']::text[], ARRAY['grind']::text[]),
  ('Cross-Body Crunch', 'Bodyweight', 1, 'No Arms', 'Abdominals', 'Beginner', 'Rotational', ARRAY['rotation']::text[], ARRAY['grind']::text[]),
  ('Oblique Crunch', 'Bodyweight', 1, 'No Arms', 'Abdominals', 'Beginner', 'Rotational', ARRAY['rotation']::text[], ARRAY['grind']::text[]),
  ('Side Jackknife', 'Bodyweight', 1, 'No Arms', 'Abdominals', 'Beginner', 'Rotational', ARRAY['rotation']::text[], ARRAY['grind']::text[]),
  ('Heel Touches', 'Bodyweight', 1, 'No Arms', 'Abdominals', 'Beginner', 'Anti-Rotation', ARRAY['core']::text[], ARRAY['grind']::text[]),
  ('Toe Touches', 'Bodyweight', 1, 'No Arms', 'Abdominals', 'Beginner', 'Anti-Extension', ARRAY['core']::text[], ARRAY['grind']::text[]),
  ('Groiners', 'Bodyweight', 1, 'Double Arm', 'Adductors', 'Intermediate', 'Anti-Extension', ARRAY['core']::text[], ARRAY['grind']::text[]),
  ('Crunch', 'Bodyweight', 1, 'No Arms', 'Abdominals', 'Beginner', 'Anti-Extension', ARRAY['core']::text[], ARRAY['grind']::text[]),
  ('Decline Crunch', 'Bodyweight', 1, 'No Arms', 'Abdominals', 'Intermediate', 'Anti-Extension', ARRAY['core']::text[], ARRAY['grind']::text[]),
  ('Reverse Crunch', 'Bodyweight', 1, 'No Arms', 'Abdominals', 'Beginner', 'Anti-Extension', ARRAY['core']::text[], ARRAY['grind']::text[]),
  ('V-Up', 'Bodyweight', 1, 'No Arms', 'Abdominals', 'Intermediate', 'Anti-Extension', ARRAY['core']::text[], ARRAY['grind']::text[]),
  ('Sit-Up', 'Bodyweight', 1, 'No Arms', 'Abdominals', 'Beginner', 'Anti-Extension', ARRAY['core']::text[], ARRAY['grind']::text[]),
  ('Jackknife Sit-Up', 'Bodyweight', 1, 'No Arms', 'Abdominals', 'Beginner', 'Anti-Extension', ARRAY['core']::text[], ARRAY['grind']::text[]),
  ('Lying Leg Raise', 'Bodyweight', 1, 'No Arms', 'Abdominals', 'Beginner', 'Anti-Extension', ARRAY['core']::text[], ARRAY['grind']::text[]),
  ('Hanging Leg Raise', 'Bodyweight', 1, 'Double Arm', 'Abdominals', 'Expert', 'Anti-Extension', ARRAY['core']::text[], ARRAY['grind']::text[]),
  ('Hanging Knee Raise', 'Bodyweight', 1, 'Double Arm', 'Abdominals', 'Intermediate', 'Anti-Extension', ARRAY['core']::text[], ARRAY['grind']::text[]),
  ('Hanging Pike', 'Bodyweight', 1, 'Double Arm', 'Abdominals', 'Expert', 'Anti-Extension', ARRAY['core']::text[], ARRAY['grind']::text[]),
  ('Toes to Bar', 'Bodyweight', 1, 'Double Arm', 'Abdominals', 'Expert', 'Anti-Extension', ARRAY['core']::text[], ARRAY['grind']::text[]),
  ('Leg Pull-In', 'Bodyweight', 1, 'No Arms', 'Abdominals', 'Beginner', 'Anti-Extension', ARRAY['core']::text[], ARRAY['grind']::text[]),
  ('Flutter Kicks', 'Bodyweight', 1, 'No Arms', 'Glutes', 'Beginner', 'Anti-Extension', ARRAY['core']::text[], ARRAY['grind']::text[]),
  ('Scissor Kick', 'Bodyweight', 1, 'No Arms', 'Abdominals', 'Beginner', 'Anti-Extension', ARRAY['core']::text[], ARRAY['grind']::text[]),
  ('Windshield Wipers', 'Bodyweight', 1, 'No Arms', 'Abdominals', 'Expert', 'Rotational', ARRAY['rotation']::text[], ARRAY['grind']::text[]),
  ('Dragon Flag', 'Bodyweight', 1, 'No Arms', 'Abdominals', 'Expert', 'Anti-Extension', ARRAY['core']::text[], ARRAY['grind']::text[]),
  ('L-Sit', 'Bodyweight', 1, 'Double Arm', 'Abdominals', 'Expert', 'Anti-Extension', ARRAY['core']::text[], ARRAY['grind']::text[]),
  ('Stomach Vacuum', 'Bodyweight', 1, 'No Arms', 'Abdominals', 'Beginner', 'Anti-Extension', ARRAY['core']::text[], ARRAY['grind']::text[]),
  ('Side Leg Raise', 'Bodyweight', 1, 'No Arms', 'Adductors', 'Beginner', 'Anti-Rotation', ARRAY['core']::text[], ARRAY['grind']::text[]),
  ('Ab Wheel Rollout', 'Bodyweight', 1, 'Double Arm', 'Abdominals', 'Intermediate', 'Anti-Extension', ARRAY['core']::text[], ARRAY['grind']::text[]),
  ('Standing Ab Wheel Rollout', 'Bodyweight', 1, 'Double Arm', 'Abdominals', 'Expert', 'Anti-Extension', ARRAY['core']::text[], ARRAY['grind']::text[]),
  ('Ab Wheel Oblique Rollout', 'Bodyweight', 1, 'Double Arm', 'Abdominals', 'Intermediate', 'Anti-Rotation', ARRAY['core']::text[], ARRAY['grind']::text[]),
  ('Reverse Plank', 'Bodyweight', 1, 'Double Arm', 'Abdominals', 'Beginner', 'Anti-Extension', ARRAY['core']::text[], ARRAY['grind']::text[]),
  ('Side Plank Hip Dip', 'Bodyweight', 1, 'Single Arm', 'Abdominals', 'Intermediate', 'Anti-Rotation', ARRAY['core']::text[], ARRAY['grind']::text[]),
  ('Hanging Windshield Wipers', 'Bodyweight', 1, 'Double Arm', 'Abdominals', 'Expert', 'Rotational', ARRAY['rotation']::text[], ARRAY['grind']::text[]),
  ('Kettlebell Plank Drag', 'Kettlebell', 1, 'Single Arm', 'Abdominals', 'Intermediate', 'Anti-Rotation', ARRAY['core']::text[], ARRAY['grind']::text[]),
  ('Pallof Press', 'Bodyweight', 1, 'Double Arm', 'Abdominals', 'Beginner', 'Anti-Rotation', ARRAY['core']::text[], ARRAY['grind']::text[]),
  ('Half-Kneeling Pallof Press', 'Bodyweight', 1, 'Double Arm', 'Abdominals', 'Intermediate', 'Anti-Rotation', ARRAY['core']::text[], ARRAY['grind']::text[]),
  ('Single-Leg Pallof Press', 'Bodyweight', 1, 'Double Arm', 'Abdominals', 'Expert', 'Anti-Rotation', ARRAY['core']::text[], ARRAY['grind']::text[])
) AS v(name, equipment, items, arm, muscle, difficulty, pattern, credits, modalities)
WHERE v.name NOT IN (SELECT "Movement" FROM public.movements);

UPDATE public.movements SET unilateral_lower = true WHERE "Movement" IN (
  'Kettlebell Single-Leg Deadlift',
  'Kettlebell Single-Leg Romanian Deadlift',
  'Kettlebell Goblet Single-Leg Romanian Deadlift',
  'Double Kettlebell Single-Leg Romanian Deadlift',
  'Kettlebell Pistol Squat',
  'Kettlebell Cossack Squat',
  'Kettlebell Goblet Reverse Lunge',
  'Kettlebell Racked Reverse Lunge',
  'Kettlebell Goblet Forward Lunge',
  'Kettlebell Racked Forward Lunge',
  'Kettlebell Goblet Walking Lunge',
  'Kettlebell Overhead Reverse Lunge',
  'Double Kettlebell Front Rack Reverse Lunge',
  'Kettlebell Curtsy Lunge',
  'Kettlebell Bulgarian Split Squat',
  'Kettlebell Front Rack Bulgarian Split Squat',
  'Double Kettlebell Bulgarian Split Squat',
  'Kettlebell Goblet Step-Up',
  'Kettlebell Lateral Lunge',
  'Kettlebell Lunge Pass Through',
  'Kettlebell Goblet Split Squat',
  'Kettlebell Racked Split Squat',
  'Kettlebell Racked Step-Up',
  'Kettlebell Goblet Curtsy Lunge',
  'Double Kettlebell Front Rack Split Squat',
  'Double Kettlebell Front Rack Step-Up',
  'Double Kettlebell Suitcase Reverse Lunge',
  'Double Kettlebell Front Rack Cossack Squat',
  'Bodyweight Pistol Squat',
  'Shrimp Squat',
  'Single-Leg Box Squat',
  'Cossack Squat',
  'Forward Lunge',
  'Reverse Lunge',
  'Walking Lunge',
  'Curtsy Lunge',
  'Lateral Lunge',
  'Bodyweight Bulgarian Split Squat',
  'Step-Up with Knee Raise',
  'Bodyweight Split Squat',
  'Bodyweight Step-Up',
  'Single-Leg Calf Raise',
  'Single-Leg Glute Bridge',
  'Single-Leg Hip Thrust',
  'Glute Kickback',
  'Donkey Kick',
  'Fire Hydrant',
  'Rear Leg Raise',
  'Bird Dog',
  'Bodyweight Single-Leg Deadlift',
  'Bodyweight Single-Leg Romanian Deadlift',
  'Single-Leg Pallof Press'
);

-- Expose the new axis to the search view PostgREST filters against.
CREATE OR REPLACE VIEW public.movements_catalog
WITH (security_invoker = true)
AS
SELECT
  id,
  "Movement" AS name,
  "Primary Equipment" AS primary_equipment,
  "# Primary Items" AS primary_item_count,
  "Single or Double Arm" AS single_or_double_arm,
  unilateral_lower
FROM public.movements;

GRANT SELECT ON public.movements_catalog TO authenticated;
