-- Modality debt Phase 1: training-modality credit on the movement catalog.
--
-- movements.modality_credits text[] names every training modality a movement
-- pays credit toward (grind / ballistic / conditioning / mobility). Source of
-- truth is scripts/data/movements.csv; this block is generated with
-- `node scripts/ingest-movements.mjs --emit-modality-sql`.
-- See docs/modality-debt-scoring-model.md.

ALTER TABLE public.movements ADD COLUMN IF NOT EXISTS modality_credits text[];


UPDATE public.movements SET modality_credits = ARRAY['ballistic', 'conditioning']::text[] WHERE "Movement" = 'Kettlebell Swing';
UPDATE public.movements SET modality_credits = ARRAY['ballistic', 'conditioning']::text[] WHERE "Movement" = 'One-Arm Kettlebell Swing';
UPDATE public.movements SET modality_credits = ARRAY['ballistic', 'conditioning']::text[] WHERE "Movement" = 'Double Kettlebell Swing';
UPDATE public.movements SET modality_credits = ARRAY['ballistic', 'conditioning']::text[] WHERE "Movement" = 'Alternating Kettlebell Swing';
UPDATE public.movements SET modality_credits = ARRAY['ballistic']::text[] WHERE "Movement" = 'Kettlebell Dead Clean';
UPDATE public.movements SET modality_credits = ARRAY['ballistic']::text[] WHERE "Movement" = 'Kettlebell Hang Clean';
UPDATE public.movements SET modality_credits = ARRAY['ballistic']::text[] WHERE "Movement" = 'One-Arm Kettlebell Clean';
UPDATE public.movements SET modality_credits = ARRAY['ballistic']::text[] WHERE "Movement" = 'Bottoms-Up Kettlebell Clean';
UPDATE public.movements SET modality_credits = ARRAY['ballistic']::text[] WHERE "Movement" = 'Bottoms-Up Kettlebell Clean From Hang';
UPDATE public.movements SET modality_credits = ARRAY['ballistic']::text[] WHERE "Movement" = 'Double Kettlebell Clean';
UPDATE public.movements SET modality_credits = ARRAY['ballistic']::text[] WHERE "Movement" = 'Double Kettlebell Dead Clean';
UPDATE public.movements SET modality_credits = ARRAY['ballistic']::text[] WHERE "Movement" = 'Double Kettlebell Alternating Hang Clean';
UPDATE public.movements SET modality_credits = ARRAY['ballistic']::text[] WHERE "Movement" = 'Alternating Kettlebell Hang Clean';
UPDATE public.movements SET modality_credits = ARRAY['ballistic', 'conditioning']::text[] WHERE "Movement" = 'One-Arm Kettlebell Snatch';
UPDATE public.movements SET modality_credits = ARRAY['ballistic', 'conditioning']::text[] WHERE "Movement" = 'One-Arm Kettlebell Split Snatch';
UPDATE public.movements SET modality_credits = ARRAY['ballistic', 'conditioning']::text[] WHERE "Movement" = 'Kettlebell Dead Snatch';
UPDATE public.movements SET modality_credits = ARRAY['ballistic', 'conditioning']::text[] WHERE "Movement" = 'Kettlebell Hang Snatch';
UPDATE public.movements SET modality_credits = ARRAY['ballistic', 'conditioning']::text[] WHERE "Movement" = 'Double Kettlebell Snatch';
UPDATE public.movements SET modality_credits = ARRAY['ballistic']::text[] WHERE "Movement" = 'Kettlebell Sumo High Pull';
UPDATE public.movements SET modality_credits = ARRAY['ballistic']::text[] WHERE "Movement" = 'One-Arm Kettlebell High Pull';
UPDATE public.movements SET modality_credits = ARRAY['ballistic']::text[] WHERE "Movement" = 'Double Kettlebell High Pull';
UPDATE public.movements SET modality_credits = ARRAY['ballistic', 'conditioning']::text[] WHERE "Movement" = 'Kettlebell Snatch Pull';
UPDATE public.movements SET modality_credits = ARRAY['mobility']::text[] WHERE "Movement" = 'Kettlebell Figure 8';
UPDATE public.movements SET modality_credits = ARRAY['mobility']::text[] WHERE "Movement" = 'Kettlebell Pass Between The Legs';
UPDATE public.movements SET modality_credits = ARRAY['mobility']::text[] WHERE "Movement" = 'Kettlebell Pirate Ships';
UPDATE public.movements SET modality_credits = ARRAY['ballistic']::text[] WHERE "Movement" = 'Kettlebell Hike Pass';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Kettlebell Deadlift';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Kettlebell Sumo Deadlift';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Kettlebell Suitcase Deadlift';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Kettlebell Romanian Deadlift';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Double Kettlebell Romanian Deadlift';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Kettlebell Single-Leg Deadlift';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Kettlebell Single-Leg Romanian Deadlift';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Kettlebell Staggered Deadlift';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Kettlebell Good Morning';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Goblet Squat';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Double Kettlebell Front Squat';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Kettlebell Pistol Squat';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'One-Arm Overhead Kettlebell Squat';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Kettlebell Front Rack Squat';
UPDATE public.movements SET modality_credits = ARRAY['grind', 'mobility']::text[] WHERE "Movement" = 'Kettlebell Cossack Squat';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Kettlebell Goblet Reverse Lunge';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Kettlebell Racked Reverse Lunge';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Kettlebell Goblet Forward Lunge';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Kettlebell Racked Forward Lunge';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Kettlebell Goblet Walking Lunge';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Kettlebell Overhead Reverse Lunge';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Double Kettlebell Front Rack Reverse Lunge';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Kettlebell Curtsy Lunge';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Kettlebell Bulgarian Split Squat';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Kettlebell Front Rack Bulgarian Split Squat';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Double Kettlebell Bulgarian Split Squat';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Kettlebell Goblet Step-Up';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Kettlebell Lateral Lunge';
UPDATE public.movements SET modality_credits = ARRAY['mobility']::text[] WHERE "Movement" = 'Kettlebell Lunge Pass Through';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Double Kettlebell Military Press';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'One-Arm Kettlebell Military Press';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Alternating Kettlebell Press';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Kettlebell Seesaw Press';
UPDATE public.movements SET modality_credits = ARRAY['ballistic']::text[] WHERE "Movement" = 'Kettlebell See-Saw Push Press';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Kettlebell Arnold Press';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Kettlebell Seated Press';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Kettlebell Half-Kneeling Press';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Kettlebell Tall-Kneeling Press';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Kettlebell Z Press';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Double Kettlebell Z Press';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'One-Arm Kettlebell Para Press';
UPDATE public.movements SET modality_credits = ARRAY['ballistic']::text[] WHERE "Movement" = 'One-Arm Kettlebell Push Press';
UPDATE public.movements SET modality_credits = ARRAY['ballistic']::text[] WHERE "Movement" = 'Double Kettlebell Push Press';
UPDATE public.movements SET modality_credits = ARRAY['ballistic']::text[] WHERE "Movement" = 'Double Kettlebell Push Jerk';
UPDATE public.movements SET modality_credits = ARRAY['ballistic']::text[] WHERE "Movement" = 'One-Arm Kettlebell Jerk';
UPDATE public.movements SET modality_credits = ARRAY['ballistic']::text[] WHERE "Movement" = 'One-Arm Kettlebell Split Jerk';
UPDATE public.movements SET modality_credits = ARRAY['ballistic', 'grind']::text[] WHERE "Movement" = 'One-Arm Kettlebell Clean and Jerk';
UPDATE public.movements SET modality_credits = ARRAY['ballistic']::text[] WHERE "Movement" = 'Double Kettlebell Jerk';
UPDATE public.movements SET modality_credits = ARRAY['ballistic', 'conditioning']::text[] WHERE "Movement" = 'Kettlebell Thruster';
UPDATE public.movements SET modality_credits = ARRAY['ballistic', 'conditioning']::text[] WHERE "Movement" = 'Double Kettlebell Thruster';
UPDATE public.movements SET modality_credits = ARRAY['ballistic', 'grind']::text[] WHERE "Movement" = 'Kettlebell Clean and Press';
UPDATE public.movements SET modality_credits = ARRAY['ballistic', 'grind']::text[] WHERE "Movement" = 'Double Kettlebell Clean and Press';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Kettlebell Sots Press';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Kettlebell Bottoms-Up Press';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Kettlebell Bent Press';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'One-Arm Kettlebell Floor Press';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Extended Range One-Arm Kettlebell Floor Press';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Leg-Over Kettlebell Floor Press';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Alternating Kettlebell Floor Press';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Double Kettlebell Floor Press';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Kettlebell Bench Press';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Double Kettlebell Bench Press';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Kettlebell Push-Up';
UPDATE public.movements SET modality_credits = ARRAY['ballistic', 'conditioning']::text[] WHERE "Movement" = 'Plyo Kettlebell Push-Up';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'One-Arm Kettlebell Row';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Double Kettlebell Row';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Alternating Kettlebell Row';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Kettlebell Renegade Row';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Alternating Renegade Row';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Kettlebell Gorilla Row';
UPDATE public.movements SET modality_credits = ARRAY['grind', 'conditioning']::text[] WHERE "Movement" = 'Kettlebell Suitcase Carry';
UPDATE public.movements SET modality_credits = ARRAY['grind', 'conditioning']::text[] WHERE "Movement" = 'Kettlebell Farmer''s Carry';
UPDATE public.movements SET modality_credits = ARRAY['grind', 'conditioning']::text[] WHERE "Movement" = 'Kettlebell Racked Carry';
UPDATE public.movements SET modality_credits = ARRAY['grind', 'conditioning']::text[] WHERE "Movement" = 'Kettlebell Double Rack Carry';
UPDATE public.movements SET modality_credits = ARRAY['grind', 'conditioning']::text[] WHERE "Movement" = 'Kettlebell Overhead Carry';
UPDATE public.movements SET modality_credits = ARRAY['grind', 'conditioning']::text[] WHERE "Movement" = 'Kettlebell Double Overhead Carry';
UPDATE public.movements SET modality_credits = ARRAY['grind', 'conditioning']::text[] WHERE "Movement" = 'Kettlebell Waiter Carry';
UPDATE public.movements SET modality_credits = ARRAY['grind', 'conditioning']::text[] WHERE "Movement" = 'Kettlebell Bottoms-Up Carry';
UPDATE public.movements SET modality_credits = ARRAY['grind', 'conditioning']::text[] WHERE "Movement" = 'Kettlebell Mixed Rack Carry';
UPDATE public.movements SET modality_credits = ARRAY['grind', 'conditioning']::text[] WHERE "Movement" = 'Kettlebell Suitcase March';
UPDATE public.movements SET modality_credits = ARRAY['grind', 'conditioning']::text[] WHERE "Movement" = 'Double Kettlebell Farmer March';
UPDATE public.movements SET modality_credits = ARRAY['grind', 'mobility']::text[] WHERE "Movement" = 'Kettlebell Windmill';
UPDATE public.movements SET modality_credits = ARRAY['grind', 'mobility']::text[] WHERE "Movement" = 'Advanced Kettlebell Windmill';
UPDATE public.movements SET modality_credits = ARRAY['grind', 'mobility']::text[] WHERE "Movement" = 'Kettlebell Overhead Windmill';
UPDATE public.movements SET modality_credits = ARRAY['grind', 'mobility']::text[] WHERE "Movement" = 'Double Kettlebell Windmill';
UPDATE public.movements SET modality_credits = ARRAY['mobility']::text[] WHERE "Movement" = 'Kettlebell Halo';
UPDATE public.movements SET modality_credits = ARRAY['mobility']::text[] WHERE "Movement" = 'Kettlebell Half-Kneeling Halo';
UPDATE public.movements SET modality_credits = ARRAY['mobility']::text[] WHERE "Movement" = 'Kettlebell Around The Body';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Kettlebell Russian Twist';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Kettlebell Wood Chop';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Kettlebell Side Bend';
UPDATE public.movements SET modality_credits = ARRAY['grind', 'mobility']::text[] WHERE "Movement" = 'Kettlebell Turkish Get-Up';
UPDATE public.movements SET modality_credits = ARRAY['grind', 'mobility']::text[] WHERE "Movement" = 'Kettlebell Turkish Get-Up (Lunge Style)';
UPDATE public.movements SET modality_credits = ARRAY['grind', 'mobility']::text[] WHERE "Movement" = 'Kettlebell Turkish Get-Up (Squat Style)';
UPDATE public.movements SET modality_credits = ARRAY['grind', 'mobility']::text[] WHERE "Movement" = 'Half Kettlebell Get-Up';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Push-Up';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Wide-Grip Push-Up';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Close-Grip Push-Up';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Diamond Push-Up';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Incline Push-Up';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Decline Push-Up';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Knee Push-Up';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Wall Push-Up';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Staggered Push-Up';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Clock Push-Up';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Spiderman Push-Up';
UPDATE public.movements SET modality_credits = ARRAY['mobility']::text[] WHERE "Movement" = 'Hindu Push-Up';
UPDATE public.movements SET modality_credits = ARRAY['ballistic', 'conditioning']::text[] WHERE "Movement" = 'Plyometric Push-Up';
UPDATE public.movements SET modality_credits = ARRAY['ballistic', 'conditioning']::text[] WHERE "Movement" = 'Clap Push-Up';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Archer Push-Up';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Pseudo Planche Push-Up';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Single-Arm Push-Up';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Push-Up to Side Plank';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Body Triceps Press';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Bench Dips';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Triceps Dips';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Straight Bar Dip';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Korean Dip';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Handstand Push-Up';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Pike Push-Up';
UPDATE public.movements SET modality_credits = ARRAY['conditioning']::text[] WHERE "Movement" = 'Wall Walk';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Wall Handstand Hold';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Pull-Up';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Chin-Up';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Neutral-Grip Pull-Up';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Wide-Grip Pull-Up';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'V-Bar Pull-Up';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Commando Pull-Up';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Scapular Pull-Up';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Negative Pull-Up';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'L-Sit Pull-Up';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Archer Pull-Up';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Muscle-Up';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Gorilla Chin-Up Crunch';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Band Pull-Down';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Single-Arm Band Pull-Down';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Inverted Row';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Wide-Grip Inverted Row';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Underhand Inverted Row';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Single-Arm Inverted Row';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Bodyweight Squat';
UPDATE public.movements SET modality_credits = ARRAY['ballistic', 'conditioning']::text[] WHERE "Movement" = 'Jump Squat';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Bodyweight Pistol Squat';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Sissy Squat';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Shrimp Squat';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Single-Leg Box Squat';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Wall Sit';
UPDATE public.movements SET modality_credits = ARRAY['grind', 'mobility']::text[] WHERE "Movement" = 'Cossack Squat';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Forward Lunge';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Reverse Lunge';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Walking Lunge';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Curtsy Lunge';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Lateral Lunge';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Bodyweight Bulgarian Split Squat';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Step-Up with Knee Raise';
UPDATE public.movements SET modality_credits = ARRAY['conditioning']::text[] WHERE "Movement" = 'Duck Walk';
UPDATE public.movements SET modality_credits = ARRAY['conditioning']::text[] WHERE "Movement" = 'High Knees';
UPDATE public.movements SET modality_credits = ARRAY['ballistic', 'conditioning']::text[] WHERE "Movement" = 'Squat Thrust';
UPDATE public.movements SET modality_credits = ARRAY['ballistic', 'conditioning']::text[] WHERE "Movement" = 'Burpee';
UPDATE public.movements SET modality_credits = ARRAY['ballistic', 'conditioning']::text[] WHERE "Movement" = 'Bench Jump';
UPDATE public.movements SET modality_credits = ARRAY['ballistic', 'conditioning']::text[] WHERE "Movement" = 'Box Jump';
UPDATE public.movements SET modality_credits = ARRAY['ballistic', 'conditioning']::text[] WHERE "Movement" = 'Freehand Jump Squat';
UPDATE public.movements SET modality_credits = ARRAY['ballistic', 'conditioning']::text[] WHERE "Movement" = 'Split Jump';
UPDATE public.movements SET modality_credits = ARRAY['ballistic', 'conditioning']::text[] WHERE "Movement" = 'Scissors Jump';
UPDATE public.movements SET modality_credits = ARRAY['ballistic', 'conditioning']::text[] WHERE "Movement" = 'Star Jump';
UPDATE public.movements SET modality_credits = ARRAY['ballistic', 'conditioning']::text[] WHERE "Movement" = 'Rocket Jump';
UPDATE public.movements SET modality_credits = ARRAY['ballistic', 'conditioning']::text[] WHERE "Movement" = 'Knee Tuck Jump';
UPDATE public.movements SET modality_credits = ARRAY['ballistic', 'conditioning']::text[] WHERE "Movement" = 'Standing Long Jump';
UPDATE public.movements SET modality_credits = ARRAY['ballistic', 'conditioning']::text[] WHERE "Movement" = 'Lateral Bound';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Standing Calf Raise';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Single-Leg Calf Raise';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Glute Bridge';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Single-Leg Glute Bridge';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Bodyweight Hip Thrust';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Single-Leg Hip Thrust';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Frog Pump';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Glute Kickback';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Donkey Kick';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Fire Hydrant';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Rear Leg Raise';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Superman';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Prone Cobra';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Bodyweight Hyperextension';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Reverse Hyperextension';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Bird Dog';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Natural Glute-Ham Raise';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Nordic Curl';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Bodyweight Good Morning';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Bodyweight Single-Leg Deadlift';
UPDATE public.movements SET modality_credits = ARRAY['mobility']::text[] WHERE "Movement" = 'Inchworm';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Plank';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Side Plank';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Bear Plank';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Plank Shoulder Tap';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Plank Up-Down';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Copenhagen Plank';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Hollow Hold';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Hollow Rock';
UPDATE public.movements SET modality_credits = ARRAY['conditioning']::text[] WHERE "Movement" = 'Mountain Climber';
UPDATE public.movements SET modality_credits = ARRAY['conditioning']::text[] WHERE "Movement" = 'Bear Crawl';
UPDATE public.movements SET modality_credits = ARRAY['conditioning']::text[] WHERE "Movement" = 'Spider Crawl';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Dead Bug';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Russian Twist';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Bicycle Crunch';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Cross-Body Crunch';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Oblique Crunch';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Side Jackknife';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Heel Touches';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Toe Touches';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Groiners';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Crunch';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Decline Crunch';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Reverse Crunch';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'V-Up';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Sit-Up';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Jackknife Sit-Up';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Lying Leg Raise';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Hanging Leg Raise';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Hanging Knee Raise';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Hanging Pike';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Toes to Bar';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Leg Pull-In';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Flutter Kicks';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Scissor Kick';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Windshield Wipers';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Dragon Flag';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'L-Sit';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Stomach Vacuum';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Side Leg Raise';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Ab Wheel Rollout';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Standing Ab Wheel Rollout';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Ab Wheel Oblique Rollout';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Reverse Plank';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Side Plank Hip Dip';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Hanging Windshield Wipers';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Kettlebell Plank Drag';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Pallof Press';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Half-Kneeling Pallof Press';
UPDATE public.movements SET modality_credits = ARRAY['grind']::text[] WHERE "Movement" = 'Single-Leg Pallof Press';
