-- Ghost pacing: race the active workout against your previous run of it.
--
-- Four changes, in order:
--   1. workout_round_splits -- the lap times. Nothing timestamped a round
--      boundary before this, so there was no data to race against.
--   2. workout_logs.program_session_id -- a provenance stamp so a program
--      workout can find its own previous run without matching on title text.
--   3. get_ghost_workout_log() -- the lookup, keyed on clone lineage rather
--      than names.
--   4. Two pre-existing RLS holes on the tables this feature touches.

-- ---------------------------------------------------------------------------
-- 1. Lap times
-- ---------------------------------------------------------------------------
-- One row per completed round. Written in bulk when the workout is logged, not
-- per round: the gym is where connectivity is worst, and the active page
-- already holds the whole session in memory.
--
-- elapsed_ms is measured from workout_logs.started_at, matching the wall-clock
-- "Elapsed" stat the active page already displays. That stat does not subtract
-- paused time, so a long mid-workout pause makes a session look slow against
-- its ghost. Both sides measure identically, so the comparison stays
-- self-consistent; making it pause-aware is a separate change.
create table public.workout_round_splits (
    "id" bigint generated by default as identity not null,
    "workout_log_id" bigint not null,
    "user_id" uuid not null,
    "round_index" smallint not null,
    "elapsed_ms" integer not null
);

alter table public.workout_round_splits enable row level security;

create unique index workout_round_splits_pkey on public.workout_round_splits using btree (id);

alter table public.workout_round_splits
  add constraint "workout_round_splits_pkey" primary key using index "workout_round_splits_pkey";

alter table public.workout_round_splits
  add constraint "workout_round_splits_workout_log_id_fkey"
  foreign key (workout_log_id) references workout_logs(id) on delete cascade not valid;
alter table public.workout_round_splits validate constraint "workout_round_splits_workout_log_id_fkey";

alter table public.workout_round_splits
  add constraint "workout_round_splits_user_id_fkey"
  foreign key (user_id) references auth.users(id) on delete cascade not valid;
alter table public.workout_round_splits validate constraint "workout_round_splits_user_id_fkey";

-- A round is logged at most once per workout. Makes a retried insert a conflict
-- rather than a silently duplicated lap.
create unique index workout_round_splits_log_round_idx
  on public.workout_round_splits using btree (workout_log_id, round_index);

-- Every read is "all splits for one log", always ordered by round.
create index workout_round_splits_log_idx
  on public.workout_round_splits using btree (workout_log_id, round_index);

-- Mirrors movement_logs, except insert is checked against the caller. See §4.
create policy "Enable read access for authenticated users"
on "public"."workout_round_splits"
as permissive for select to authenticated
using ((auth.uid() = user_id));

create policy "Enable insert for users based on user_id"
on "public"."workout_round_splits"
as permissive for insert to authenticated
with check ((auth.uid() = user_id));

create policy "Enable update for authenticated users"
on "public"."workout_round_splits"
as permissive for update to authenticated
using ((auth.uid() = user_id))
with check ((auth.uid() = user_id));

create policy "Enable delete for users based on user_id"
on "public"."workout_round_splits"
as permissive for delete to authenticated
using ((auth.uid() = user_id));

-- ---------------------------------------------------------------------------
-- 2. Program provenance on the log
-- ---------------------------------------------------------------------------
-- docs/program-tracking.md says the program linkage is deliberately NOT a
-- workout_logs column, and that still holds for PROGRESS:
-- program_session_completions remains the sole source of truth for what a user
-- has finished. This column is provenance, not progress -- it records which
-- prescription produced this log, so a later run can find it. The two differ in
-- lifetime, which is the whole point: complete_program_session DELETES all
-- completions when an auto-repeat program loops (20260727000002), and that wipe
-- is exactly when a ghost is most wanted.
--
-- ON DELETE SET NULL: deleting a program session should orphan the ghost link,
-- never the workout history.
alter table public.workout_logs
  add column "program_session_id" uuid;

alter table public.workout_logs
  add constraint "workout_logs_program_session_id_fkey"
  foreign key (program_session_id) references program_sessions(id) on delete set null not valid;
alter table public.workout_logs validate constraint "workout_logs_program_session_id_fkey";

create index workout_logs_program_session_idx
  on public.workout_logs using btree (program_session_id)
  where program_session_id is not null;

-- ---------------------------------------------------------------------------
-- 3. Ghost lookup
-- ---------------------------------------------------------------------------
-- Finding "my previous run of this program session" cannot key on the composed
-- "{Program} · W#D# {title}" string: renaming a program orphans every prior log,
-- and the format is a helper away from changing.
--
-- A plain program_session_id FK comparison is not enough either. enroll_in_program
-- is copy-on-enroll -- enrolling in the same shared program twice CLONES programs
-- and every program_sessions row with fresh UUIDs -- so cycle 2's session id never
-- equals cycle 1's.
--
-- The durable key is (root_program_id, sequence_index):
--   * sequence_index is UNIQUE (program_id, sequence_index) and is pure position.
--     It is never renamed and never user-edited.
--   * root_program_id = coalesce(source_program_id, id) collapses every clone of a
--     shared program back onto its origin, using lineage already recorded at enroll.
--
-- Survives renames, the auto-repeat completions wipe, and re-enrollment.
--
-- Known limit: source_program_id is ON DELETE SET NULL, so hard-deleting an origin
-- program makes each surviving clone its own root. Ghosts then stop crossing
-- between enrollments -- a graceful degradation to per-enrollment matching, not a
-- broken query.
--
-- SECURITY INVOKER: RLS on workout_logs already scopes this to the caller. The
-- explicit user_id predicate is belt-and-braces and keeps the intent readable.
create or replace function public.get_ghost_workout_log(
  p_program_session_id uuid,
  p_exclude_workout_log_id bigint default null
)
returns setof public.workout_logs
language sql
stable
security invoker
set search_path = public
as $$
  with target as (
    select
      coalesce(p.source_program_id, p.id) as root_program_id,
      ps.sequence_index
    from program_sessions ps
    join programs p on p.id = ps.program_id
    where ps.id = p_program_session_id
  )
  select wl.*
  from workout_logs wl
  join program_sessions ps on ps.id = wl.program_session_id
  join programs p on p.id = ps.program_id
  join target t
    on coalesce(p.source_program_id, p.id) = t.root_program_id
   and ps.sequence_index = t.sequence_index
  where wl.user_id = auth.uid()
    and wl.id is distinct from p_exclude_workout_log_id
  order by wl.started_at desc
  limit 1;
$$;

-- ---------------------------------------------------------------------------
-- 4. RLS holes on the tables this feature touches
-- ---------------------------------------------------------------------------
-- Both policies below guarded the row being MODIFIED but not the row being
-- WRITTEN, so a user could attribute a row to another account -- writing into
-- someone else's history, or handing away their own. Policies are dropped and
-- recreated under their original names so the next `supabase db diff` stays clean.
--
-- Safe to tighten: useLogWorkout sets user_id from the authenticated session, and
-- the three workout_logs update paths (useSelectRPE, useUpdatePostWorkoutNotes,
-- useDeleteWorkoutLog) never touch user_id.

-- movement_logs insert was `with check (true)`: any authenticated user could
-- insert a movement row attributed to anyone.
drop policy "Enable insert for authenticated users only" on "public"."movement_logs";

create policy "Enable insert for authenticated users only"
on "public"."movement_logs"
as permissive for insert to authenticated
with check ((auth.uid() = user_id));

-- workout_logs update was `using (auth.uid() = user_id) with check (true)`: the
-- using clause stopped you editing someone else's row, but the check let you
-- reassign your OWN row's user_id to another account.
drop policy "Enable update access for workout logs based on user id" on "public"."workout_logs";

create policy "Enable update access for workout logs based on user id"
on "public"."workout_logs"
as permissive for update to authenticated
using ((auth.uid() = user_id))
with check ((auth.uid() = user_id));
