-- Skill-tree node each catalog movement practises (PROD-249 follow-up): the
-- recommenders use it as a deterministic ceiling, so a lifter is never handed a
-- movement whose node is beyond their self-assessed frontier. NULL means the
-- movement practises no node and is never gated. Mapping rule: the hardest node
-- the movement requires, never a mobility (Lx-M1) node when a movement node is
-- needed to get into the position.
--
-- Source of truth is scripts/data/movements.csv; the UPDATE block below is
-- generated with `npm run movements:emit-skill-node-sql`.

ALTER TABLE public.movements ADD COLUMN IF NOT EXISTS skill_node_id text;

UPDATE public.movements SET skill_node_id = 'L2-N2' WHERE "Movement" = 'Kettlebell Swing';
UPDATE public.movements SET skill_node_id = 'L3-N1' WHERE "Movement" = 'One-Arm Kettlebell Swing';
UPDATE public.movements SET skill_node_id = 'L6-N3' WHERE "Movement" = 'Double Kettlebell Swing';
UPDATE public.movements SET skill_node_id = 'L3-N1' WHERE "Movement" = 'Alternating Kettlebell Swing';
UPDATE public.movements SET skill_node_id = 'L4-N1' WHERE "Movement" = 'Kettlebell Dead Clean';
UPDATE public.movements SET skill_node_id = 'L4-N1' WHERE "Movement" = 'Kettlebell Hang Clean';
UPDATE public.movements SET skill_node_id = 'L4-N1' WHERE "Movement" = 'One-Arm Kettlebell Clean';
UPDATE public.movements SET skill_node_id = 'L4-N1' WHERE "Movement" = 'Bottoms-Up Kettlebell Clean';
UPDATE public.movements SET skill_node_id = 'L4-N1' WHERE "Movement" = 'Bottoms-Up Kettlebell Clean From Hang';
UPDATE public.movements SET skill_node_id = 'L7-N1' WHERE "Movement" = 'Double Kettlebell Clean';
UPDATE public.movements SET skill_node_id = 'L7-N1' WHERE "Movement" = 'Double Kettlebell Dead Clean';
UPDATE public.movements SET skill_node_id = 'L7-N1' WHERE "Movement" = 'Double Kettlebell Alternating Hang Clean';
UPDATE public.movements SET skill_node_id = 'L7-N1' WHERE "Movement" = 'Alternating Kettlebell Hang Clean';
UPDATE public.movements SET skill_node_id = 'L8-N1' WHERE "Movement" = 'One-Arm Kettlebell Snatch';
UPDATE public.movements SET skill_node_id = 'L8-N1' WHERE "Movement" = 'One-Arm Kettlebell Split Snatch';
UPDATE public.movements SET skill_node_id = 'L8-N1' WHERE "Movement" = 'Kettlebell Dead Snatch';
UPDATE public.movements SET skill_node_id = 'L8-N1' WHERE "Movement" = 'Kettlebell Hang Snatch';
UPDATE public.movements SET skill_node_id = 'L9-N1' WHERE "Movement" = 'Double Kettlebell Snatch';
UPDATE public.movements SET skill_node_id = 'L2-N2' WHERE "Movement" = 'Kettlebell Sumo High Pull';
UPDATE public.movements SET skill_node_id = 'L3-N1' WHERE "Movement" = 'One-Arm Kettlebell High Pull';
UPDATE public.movements SET skill_node_id = 'L6-N3' WHERE "Movement" = 'Double Kettlebell High Pull';
UPDATE public.movements SET skill_node_id = 'L8-N1' WHERE "Movement" = 'Kettlebell Snatch Pull';
UPDATE public.movements SET skill_node_id = 'L2-N1' WHERE "Movement" = 'Kettlebell Figure 8';
UPDATE public.movements SET skill_node_id = 'L2-N1' WHERE "Movement" = 'Kettlebell Pass Between The Legs';
UPDATE public.movements SET skill_node_id = 'L2-N1' WHERE "Movement" = 'Kettlebell Pirate Ships';
UPDATE public.movements SET skill_node_id = 'L2-N2' WHERE "Movement" = 'Kettlebell Hike Pass';
UPDATE public.movements SET skill_node_id = 'L2-N1' WHERE "Movement" = 'Kettlebell Deadlift';
UPDATE public.movements SET skill_node_id = 'L2-N1' WHERE "Movement" = 'Kettlebell Sumo Deadlift';
UPDATE public.movements SET skill_node_id = 'L2-N3' WHERE "Movement" = 'Kettlebell Suitcase Deadlift';
UPDATE public.movements SET skill_node_id = 'L2-N3' WHERE "Movement" = 'Kettlebell Romanian Deadlift';
UPDATE public.movements SET skill_node_id = 'L2-N3' WHERE "Movement" = 'Double Kettlebell Romanian Deadlift';
UPDATE public.movements SET skill_node_id = 'L2-N1' WHERE "Movement" = 'Kettlebell Single-Leg Deadlift';
UPDATE public.movements SET skill_node_id = 'L2-N1' WHERE "Movement" = 'Kettlebell Single-Leg Romanian Deadlift';
UPDATE public.movements SET skill_node_id = 'L2-N1' WHERE "Movement" = 'Kettlebell Goblet Single-Leg Romanian Deadlift';
UPDATE public.movements SET skill_node_id = 'L2-N3' WHERE "Movement" = 'Double Kettlebell Single-Leg Romanian Deadlift';
UPDATE public.movements SET skill_node_id = 'L2-N1' WHERE "Movement" = 'Kettlebell Staggered Deadlift';
UPDATE public.movements SET skill_node_id = 'L2-N1' WHERE "Movement" = 'Kettlebell Good Morning';
UPDATE public.movements SET skill_node_id = 'L1-N3' WHERE "Movement" = 'Goblet Squat';
UPDATE public.movements SET skill_node_id = 'L7-N2' WHERE "Movement" = 'Double Kettlebell Front Squat';
UPDATE public.movements SET skill_node_id = 'L5-N2' WHERE "Movement" = 'Kettlebell Pistol Squat';
UPDATE public.movements SET skill_node_id = 'L5-N3' WHERE "Movement" = 'One-Arm Overhead Kettlebell Squat';
UPDATE public.movements SET skill_node_id = 'L4-N4' WHERE "Movement" = 'Kettlebell Front Rack Squat';
UPDATE public.movements SET skill_node_id = 'L5-N2' WHERE "Movement" = 'Kettlebell Cossack Squat';
UPDATE public.movements SET skill_node_id = 'L1-N3' WHERE "Movement" = 'Kettlebell Goblet Reverse Lunge';
UPDATE public.movements SET skill_node_id = 'L4-N4' WHERE "Movement" = 'Kettlebell Racked Reverse Lunge';
UPDATE public.movements SET skill_node_id = 'L1-N3' WHERE "Movement" = 'Kettlebell Goblet Forward Lunge';
UPDATE public.movements SET skill_node_id = 'L4-N4' WHERE "Movement" = 'Kettlebell Racked Forward Lunge';
UPDATE public.movements SET skill_node_id = 'L1-N3' WHERE "Movement" = 'Kettlebell Goblet Walking Lunge';
UPDATE public.movements SET skill_node_id = 'L4-N3' WHERE "Movement" = 'Kettlebell Overhead Reverse Lunge';
UPDATE public.movements SET skill_node_id = 'L7-N2' WHERE "Movement" = 'Double Kettlebell Front Rack Reverse Lunge';
UPDATE public.movements SET skill_node_id = 'L1-N3' WHERE "Movement" = 'Kettlebell Curtsy Lunge';
UPDATE public.movements SET skill_node_id = 'L1-N3' WHERE "Movement" = 'Kettlebell Bulgarian Split Squat';
UPDATE public.movements SET skill_node_id = 'L4-N4' WHERE "Movement" = 'Kettlebell Front Rack Bulgarian Split Squat';
UPDATE public.movements SET skill_node_id = 'L7-N2' WHERE "Movement" = 'Double Kettlebell Bulgarian Split Squat';
UPDATE public.movements SET skill_node_id = 'L1-N3' WHERE "Movement" = 'Kettlebell Goblet Step-Up';
UPDATE public.movements SET skill_node_id = 'L1-N3' WHERE "Movement" = 'Kettlebell Lateral Lunge';
UPDATE public.movements SET skill_node_id = 'L1-N3' WHERE "Movement" = 'Kettlebell Lunge Pass Through';
UPDATE public.movements SET skill_node_id = 'L1-N3' WHERE "Movement" = 'Kettlebell Goblet Split Squat';
UPDATE public.movements SET skill_node_id = 'L4-N4' WHERE "Movement" = 'Kettlebell Racked Split Squat';
UPDATE public.movements SET skill_node_id = 'L4-N4' WHERE "Movement" = 'Kettlebell Racked Step-Up';
UPDATE public.movements SET skill_node_id = 'L1-N3' WHERE "Movement" = 'Kettlebell Goblet Curtsy Lunge';
UPDATE public.movements SET skill_node_id = 'L7-N2' WHERE "Movement" = 'Double Kettlebell Front Rack Split Squat';
UPDATE public.movements SET skill_node_id = 'L7-N2' WHERE "Movement" = 'Double Kettlebell Front Rack Step-Up';
UPDATE public.movements SET skill_node_id = 'L2-N3' WHERE "Movement" = 'Double Kettlebell Suitcase Reverse Lunge';
UPDATE public.movements SET skill_node_id = 'L7-N2' WHERE "Movement" = 'Double Kettlebell Front Rack Cossack Squat';
UPDATE public.movements SET skill_node_id = 'L7-N3' WHERE "Movement" = 'Double Kettlebell Military Press';
UPDATE public.movements SET skill_node_id = 'L4-N3' WHERE "Movement" = 'One-Arm Kettlebell Military Press';
UPDATE public.movements SET skill_node_id = 'L7-N3' WHERE "Movement" = 'Alternating Kettlebell Press';
UPDATE public.movements SET skill_node_id = 'L7-N3' WHERE "Movement" = 'Kettlebell Seesaw Press';
UPDATE public.movements SET skill_node_id = 'L7-N3' WHERE "Movement" = 'Kettlebell See-Saw Push Press';
UPDATE public.movements SET skill_node_id = 'L4-N3' WHERE "Movement" = 'Kettlebell Arnold Press';
UPDATE public.movements SET skill_node_id = 'L4-N3' WHERE "Movement" = 'Kettlebell Seated Press';
UPDATE public.movements SET skill_node_id = 'L4-N2' WHERE "Movement" = 'Kettlebell Half-Kneeling Press';
UPDATE public.movements SET skill_node_id = 'L4-N2' WHERE "Movement" = 'Kettlebell Tall-Kneeling Press';
UPDATE public.movements SET skill_node_id = 'L4-N3' WHERE "Movement" = 'Kettlebell Z Press';
UPDATE public.movements SET skill_node_id = 'L7-N3' WHERE "Movement" = 'Double Kettlebell Z Press';
UPDATE public.movements SET skill_node_id = 'L4-N3' WHERE "Movement" = 'One-Arm Kettlebell Para Press';
UPDATE public.movements SET skill_node_id = 'L5-N4' WHERE "Movement" = 'One-Arm Kettlebell Push Press';
UPDATE public.movements SET skill_node_id = 'L7-N3' WHERE "Movement" = 'Double Kettlebell Push Press';
UPDATE public.movements SET skill_node_id = 'L8-N3' WHERE "Movement" = 'Double Kettlebell Push Jerk';
UPDATE public.movements SET skill_node_id = 'L5-N4' WHERE "Movement" = 'One-Arm Kettlebell Jerk';
UPDATE public.movements SET skill_node_id = 'L5-N4' WHERE "Movement" = 'One-Arm Kettlebell Split Jerk';
UPDATE public.movements SET skill_node_id = 'L5-N4' WHERE "Movement" = 'One-Arm Kettlebell Clean and Jerk';
UPDATE public.movements SET skill_node_id = 'L8-N3' WHERE "Movement" = 'Double Kettlebell Jerk';
UPDATE public.movements SET skill_node_id = 'L4-N3' WHERE "Movement" = 'Kettlebell Thruster';
UPDATE public.movements SET skill_node_id = 'L7-N3' WHERE "Movement" = 'Double Kettlebell Thruster';
UPDATE public.movements SET skill_node_id = 'L4-N3' WHERE "Movement" = 'Kettlebell Clean and Press';
UPDATE public.movements SET skill_node_id = 'L7-N3' WHERE "Movement" = 'Double Kettlebell Clean and Press';
UPDATE public.movements SET skill_node_id = 'L5-N3' WHERE "Movement" = 'Kettlebell Sots Press';
UPDATE public.movements SET skill_node_id = 'L4-N3' WHERE "Movement" = 'Kettlebell Bottoms-Up Press';
UPDATE public.movements SET skill_node_id = 'L6-N2' WHERE "Movement" = 'Kettlebell Bent Press';
UPDATE public.movements SET skill_node_id = 'L3-N2' WHERE "Movement" = 'Kettlebell Suitcase Carry';
UPDATE public.movements SET skill_node_id = 'L2-N3' WHERE "Movement" = 'Kettlebell Farmer''s Carry';
UPDATE public.movements SET skill_node_id = 'L4-N4' WHERE "Movement" = 'Kettlebell Racked Carry';
UPDATE public.movements SET skill_node_id = 'L7-N1' WHERE "Movement" = 'Kettlebell Double Rack Carry';
UPDATE public.movements SET skill_node_id = 'L4-N3' WHERE "Movement" = 'Kettlebell Overhead Carry';
UPDATE public.movements SET skill_node_id = 'L7-N3' WHERE "Movement" = 'Kettlebell Double Overhead Carry';
UPDATE public.movements SET skill_node_id = 'L4-N3' WHERE "Movement" = 'Kettlebell Waiter Carry';
UPDATE public.movements SET skill_node_id = 'L4-N1' WHERE "Movement" = 'Kettlebell Bottoms-Up Carry';
UPDATE public.movements SET skill_node_id = 'L7-N3' WHERE "Movement" = 'Kettlebell Mixed Rack Carry';
UPDATE public.movements SET skill_node_id = 'L3-N2' WHERE "Movement" = 'Kettlebell Suitcase March';
UPDATE public.movements SET skill_node_id = 'L2-N3' WHERE "Movement" = 'Double Kettlebell Farmer March';
UPDATE public.movements SET skill_node_id = 'L5-N3' WHERE "Movement" = 'Kettlebell Windmill';
UPDATE public.movements SET skill_node_id = 'L6-N2' WHERE "Movement" = 'Advanced Kettlebell Windmill';
UPDATE public.movements SET skill_node_id = 'L6-N2' WHERE "Movement" = 'Kettlebell Overhead Windmill';
UPDATE public.movements SET skill_node_id = 'L6-N2' WHERE "Movement" = 'Double Kettlebell Windmill';
UPDATE public.movements SET skill_node_id = 'L3-M1' WHERE "Movement" = 'Kettlebell Halo';
UPDATE public.movements SET skill_node_id = 'L3-M1' WHERE "Movement" = 'Kettlebell Half-Kneeling Halo';
UPDATE public.movements SET skill_node_id = 'L1-N5' WHERE "Movement" = 'Kettlebell Around The Body';
UPDATE public.movements SET skill_node_id = 'L6-N1' WHERE "Movement" = 'Kettlebell Turkish Get-Up';
UPDATE public.movements SET skill_node_id = 'L6-N1' WHERE "Movement" = 'Kettlebell Turkish Get-Up (Lunge Style)';
UPDATE public.movements SET skill_node_id = 'L6-N1' WHERE "Movement" = 'Kettlebell Turkish Get-Up (Squat Style)';
UPDATE public.movements SET skill_node_id = 'L5-N1' WHERE "Movement" = 'Half Kettlebell Get-Up';
UPDATE public.movements SET skill_node_id = 'L1-N3' WHERE "Movement" = 'Bodyweight Squat';
UPDATE public.movements SET skill_node_id = 'L5-N2' WHERE "Movement" = 'Bodyweight Pistol Squat';
UPDATE public.movements SET skill_node_id = 'L2-M1' WHERE "Movement" = 'Cossack Squat';
UPDATE public.movements SET skill_node_id = 'L1-N4' WHERE "Movement" = 'Bird Dog';
UPDATE public.movements SET skill_node_id = 'L1-N2' WHERE "Movement" = 'Bodyweight Good Morning';
UPDATE public.movements SET skill_node_id = 'L1-N6' WHERE "Movement" = 'Bodyweight Single-Leg Deadlift';
UPDATE public.movements SET skill_node_id = 'L1-N6' WHERE "Movement" = 'Bodyweight Single-Leg Romanian Deadlift';
UPDATE public.movements SET skill_node_id = 'L1-N1' WHERE "Movement" = 'Plank';
UPDATE public.movements SET skill_node_id = 'L1-N1' WHERE "Movement" = 'Side Plank';
UPDATE public.movements SET skill_node_id = 'L1-N4' WHERE "Movement" = 'Hollow Hold';
UPDATE public.movements SET skill_node_id = 'L1-N4' WHERE "Movement" = 'Dead Bug';
UPDATE public.movements SET skill_node_id = 'L1-N1' WHERE "Movement" = 'Kettlebell Plank Drag';
